= Definiciones de la capacidad del servicio de Keystone
:allow-uri-read: 


---definiciones barra lateral: enlace lateral permalink: nkfsosm_keystone_service_capacity_definitions.html palabras clave: netapp, keystone, servicio, capacidad, definiciones, Ráfaga, capacidad comprometida, capacidad consumida, resumen de la capacidad facturada: Definiciones de capacidad del servicio de Keystone ---



= Definiciones de la capacidad del servicio de Keystone

[role="lead"]
Las capacidades del servicio NetApp Keystone incluyen:



== Capacidad lógica

Estos son los datos que un cliente coloca en la infraestructura de Keystone. Todas las capacidades de Keystone se refieren a una capacidad lógica. Por ejemplo, si se almacena un archivo de 1 TiB en la infraestructura Keystone, deben comprarse al menos 1 TiB de capacidad.



== Capacidad comprometida

La capacidad lógica mínima que se factura cada mes durante el periodo:

* La capacidad se compromete con cada nivel de servicio.
* La capacidad comprometida no puede disminuir durante este periodo.
* Durante el período de vigencia se puede añadir la capacidad comprometida y los niveles de servicio adicionales.




=== Cambios en la capacidad comprometida

Durante la duración de una suscripción, puede cambiar las capacidades comprometidas. Sin embargo, existen algunas condiciones previas:

* No es posible reducir la capacidad proporcionada
* La capacidad comprometida no puede aumentarse 90 días antes del vencimiento de la suscripción, a menos que la suscripción se renueve por un plazo adicional de 12 meses.
* Puede solicitar cambios en la capacidad comprometida a través de la interfaz del motor de servicio de NetApp o a través de Keystone Success Manager. Para obtener información acerca de cómo solicitar cambios, consulte link:sewebiug_raise_a_service_request.html["Elevar una solicitud de servicio"].




== Capacidad de ráfaga

Esta es la capacidad lógica que ha superado la capacidad comprometida. Tenga en cuenta lo siguiente:

* El servicio Keystone ofrece una capacidad que supera el 20 % de la capacidad comprometida.
* La capacidad de ráfaga se puede consumir sobre una base flexible y se cobra diariamente por la media consumida.
* Hasta un 20 % de la capacidad de ráfaga se carga a la misma tasa que la capacidad comprometida.
* Una capacidad de ráfaga superior al 20 % del compromiso se cobra a una tasa premium. Póngase en contacto con el soporte para cualquier requisito de ráfaga adicional superior al 20 %.




== Capacidad consumida/aprovisionada

La capacidad consumida hace referencia a la capacidad en TIB del almacenamiento que se está consumiendo actualmente en el servicio. El servicio Keystone considera la suma de los tamaños aprovisionados (no la capacidad lógica o física usada) de todos los volúmenes de un nivel de servicio particular para considerarse como capacidad consumida para ese nivel de servicio. Estos recursos incluyen:

* La capacidad que se aprovisiona mediante la creación, la modificación, la eliminación o el posible crecimiento automático de los volúmenes.
* Las copias y los clones Snapshot.
+

NOTE: No se tiene en cuenta la cantidad de datos almacenados dentro de la capacidad aprovisionada o la cantidad de datos escritos en el disco.





== Capacidad facturada

Factura mensual = (capacidad comprometida [TIB] * tasa comprometida [$/TIB]) + (capacidad de ráfaga aprovisionada media diaria [TIB] * tasa de ráfaga [$/TIB]). La factura mensual contiene un cargo mínimo basado en la capacidad comprometida.

La factura mensual varía más allá del cargo mínimo en función del consumo medio de capacidad de ráfaga diaria. Para obtener más información sobre facturación, consulte link:nkfsosm_kfs_billing.html["Facturación de Keystone"].
