---
sidebar: sidebar 
permalink: nkfsosm_performance.html 
keywords: netapp, keystone, performance, service levels 
summary: Keystone realiza el nivel de servicio 
---
= Niveles de servicio
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Keystone ofrece capacidad de almacenamiento de datos con niveles de servicio de rendimiento predefinidos (niveles de servicio) o planes de tarifas basados en la suscripción. Cada volumen gestionado por los servicios de Keystone se asocia con un nivel de servicio.

Cada nivel de servicio está definido por su densidad de I/O, que es IOPS/TiB/volumen. Esta es la proporción de rendimiento (operaciones de entrada/salida por segundo [IOPS]) y capacidad de almacenamiento asignada (TiB), que es IOPS/TiB con latencia media por volumen.

La densidad de I/O de un volumen se calcula en un intervalo por hora para informar sobre la densidad máxima de I/O. Los informes de densidad de I/O para los volúmenes se generan mensualmente.

Aquí se enumeran los niveles de servicio para los tipos de almacenamiento de archivos, bloques y objetos.



== Niveles de servicio para el almacenamiento de archivos

*Protocolos compatibles*: NFS, CIFS, iSCSI y FC

|===


| *Nivel de servicio* | *Extremo* | *Premium* | *Estándar* | *Valor* 


| *Tipo de carga de trabajo* | Análisis, bases de datos | VDI, aplicaciones de virtualización, desarrollo de software | Archivos compartidos, servidores web | Backup 


| *Máximo IOPS/TiB lógico asignado por volumen* | 12,288 | 4,096 | 512 | N.A. 


| *Objetivo IOPS/TiB lógico asignado por volumen* | 6,144 | 2,048 | 128 | N.A. 


| *Máximo Mbps/TiB lógico asignado por volumen* | 384 | 128 | 16 | N.A. 


| *Latencia media* | <1 ms | <2 ms | <17 ms | N.A. 


| *Tamaño del bloque* 4+| 32K 
|===


=== Más información sobre niveles de servicio para el almacenamiento de archivos

Las métricas de nivel de servicio dependen de las siguientes condiciones:

* Los niveles de servicio del almacenamiento de archivos y bloques son compatibles con ONTAP 9,7 y versiones posteriores.
* Los valores de IOPS/TiB/volumen, MBps/TiB/volumen y latencia para los niveles de servicio se basan en la cantidad de datos lógicos almacenados en el volumen, el tamaño de bloque de 32KB KB y una combinación aleatoria de operaciones de I/O de lectura al 70 % y 30 % en escritura.
* Las operaciones de IOPS/TiB/volumen reales y MBps/TiB/volumen pueden variar en función del tamaño de bloque real o asumido, la concurrencia de la carga de trabajo del sistema o las operaciones de entrada y salida.
* La latencia no incluye lo siguiente:
+
** latencia de aplicaciones o host
** latencia de red del cliente hacia o desde los puertos de la controladora
** Costes generales asociados a la transferencia de datos al almacén de objetos, en caso de FabricPool
** La calidad de servicio aplica automáticamente la latencia para mantener el I/O dentro de los máximos niveles de servicio


* Los valores de latencia no son aplicables a las operaciones de escritura de MetroCluster. Estas operaciones de escritura dependen de la distancia de los sistemas remotos.
* Si uno o varios volúmenes de un sistema de almacenamiento no tienen asignada una política de calidad de servicio, estos volúmenes se consideran como volúmenes que no cumplen las normativas y no son aplicables a dichos sistemas.
* _Expected IOPS_ está dirigido a FabricPool solo si la política de organización en niveles se establece en «ninguno» y no hay bloques en el cloud. _Expected IOPS_ se dirige a volúmenes que no están en una relación de SnapMirror síncrona.
* Las operaciones de I/O de carga de trabajo deben equilibrarse en todas las controladoras puestas en marcha, según lo determine el orden de Keystone.




== Niveles de servicio para el almacenamiento en bloques

*Protocolos compatibles*: FC e iSCSI

|===


| *Nivel de servicio* | *Extremo* | *Premium* | *Estándar* 


| *Tipo de carga de trabajo* | HPC | Videovigilancia | Backup 


| *IOPS/TIB* objetivo 3+| N.A. 


| *IOPS máx./TIB* | 5.500 | 4,000 | N.A. 


| *Rendimiento máximo en Mbps (32 KB/IOP)* | 43 | 31 | N.A. 


| *Latencia media* | <0.5 ms | <0.5 ms | N.A. 


| *Tamaño del bloque* 3+| 32K 
|===


== Niveles de servicio para el almacenamiento de objetos

*Protocolo admitido*: S3

|===


| *Nivel de servicio* | Objeto 


| *Tipo de carga de trabajo* | Almacén de medios, archivado 


| *IOPS/TIB* objetivo | N.A. 


| *IOPS máx./TIB* | N.A. 


| *Rendimiento máximo en Mbps (32 KB/IOP)* | N.A. 


| *Latencia media* | N.A. 
|===