---
sidebar: sidebar 
permalink: nkfsosm_performance.html 
keywords: netapp, keystone, performance, 
summary: Rendimiento de la suscripción Keystone Flex 
---
= Niveles de servicio
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La suscripción flexible de NetApp Keystone (suscripción flexible) ofrece capacidad con niveles de servicio de rendimiento predefinidos (niveles de servicio).

Cada nivel de servicio está definido por su densidad de I/o, que es la proporción de rendimiento (operaciones de entrada/salida por segundo [IOPS]) y almacenamiento utilizado (TIB de datos almacenados), que es IOPS/TIB.

Cada volumen gestionado por los servicios de suscripción Flex está asociado a un nivel de servicio. Todas las operaciones de E/S y todo el almacenamiento usado en el volumen correspondiente se incluyen en el cálculo de la densidad de E/S del volumen.

En la tabla siguiente se definen los niveles de servicio.



== Niveles de servicio para distintos tipos de almacenamiento

Aquí se muestran los niveles de servicio para el almacenamiento de archivos, bloques y objetos.

Se informa de los cálculos de densidad de I/o en el nivel del volumen para mostrar la densidad de I/o máxima durante la semana anterior. El rendimiento máximo se determina en un intervalo de tiempo por hora. Los informes de densidad de I/o por volumen se generan mensualmente para medir el cumplimiento de los niveles de servicio correspondientes.



=== Servicio de ficheros

*Protocolos compatibles*: NFS, CIFS, iSCSI y FC

|===


| *Nivel de servicio* | *Extremo* | *Premium* | *Estándar* | *Valor* 


| *Tipo de carga de trabajo* | Análisis, bases de datos | VDI, aplicaciones de virtualización, desarrollo de software | Archivos compartidos, servidores web | Backup 


| *IOPS/TIB* objetivo | 6,144 | 2,048 | 128 | N.A. 


| *IOPS máx./TIB* | 12,288 | 4,096 | 512 | N.A. 


| *Rendimiento máximo en Mbps (32 KB/IOP)* | 384 | 128 | 16 | N.A. 


| *Latencia* | <1 ms | <2 ms | <17 ms | N.A. 


.2+| *Capacidad mínima* 1,2 4+| 100 TIB 1 


| 15 TIB 2 | 25 TIB 2 | 50 TIB 2 | 50 TIB 2 
|===

NOTE: Este 1 plazo mínimo de un año y una capacidad mínima de 100 TIB para una combinación de cualquier recurso compartido de archivos y niveles de servicio de bloque para oportunidades directas de NetApp. Plazo mínimo de un año y capacidad mínima establecida por cada nivel de servicio seleccionado para las oportunidades de canales.



=== Almacenamiento en bloques

*Protocolos compatibles*: FC e iSCSI

|===


| *Nivel de servicio* | *Extremo* | *Premium* | *Estándar* 


| *Tipo de carga de trabajo* | HPC | Videovigilancia | Backup 


| *IOPS/TIB* objetivo 3+| N.A. 


| *IOPS máx./TIB* | 5.500 | 4,000 | N.A. 


| *Rendimiento máximo en Mbps (32 KB/IOP)* | 43 | 31 | N.A. 


| *Latencia* | <0.5 ms | <0.5 ms | N.A. 


| *Capacidad mínima* 1,2 | 100 TIB 3 | 100 TIB 3 | 300 TIB 3 
|===

NOTE: Este 1 plazo mínimo de un año y una capacidad mínima de 100 TIB para una combinación de cualquier recurso compartido de archivos y niveles de servicio de bloque para oportunidades directas de NetApp. Plazo mínimo de un año y capacidad mínima establecida por nivel de servicio seleccionados para las oportunidades de canales. El plazo mínimo de un año y la capacidad mínima indicada por cada nivel de servicio seleccionados para cualquier tipo de oportunidad se establecen en 3.



=== Almacenamiento de objetos

*Protocolo admitido*: S3

|===


| *Nivel de servicio* | Objeto 


| *Tipo de carga de trabajo* | Almacén de medios, archivado 


| *IOPS/TIB* objetivo | N.A. 


| *IOPS máx./TIB* | N.A. 


| *Rendimiento máximo en Mbps (32 KB/IOP)* | N.A. 


| *Latencia* | N.A. 


| *Capacidad mínima* 1,2 | 500 TIB 3 
|===

NOTE: Este 1 plazo mínimo de un año y una capacidad mínima de 100 TIB para una combinación de cualquier recurso compartido de archivos y niveles de servicio de bloque para oportunidades directas de NetApp. Plazo mínimo de un año y capacidad mínima establecida por nivel de servicio seleccionados para las oportunidades de canales. El plazo mínimo de un año y la capacidad mínima indicada por cada nivel de servicio seleccionados para cualquier tipo de oportunidad se establecen en 3.

Puede asignar niveles de servicio a sus suscripciones desde varias pantallas de la interfaz de usuario del motor de servicios de NetApp. Para obtener más información, consulte link:nkfsosm_tenancy_overview.html["Soporte para multi-tenancy y suscripción flexible"].
