---
sidebar: sidebar 
permalink: nkfsosm_kfs_billing.html 
keywords: netapp, keystone, billing, Keystone billing logic, charges, charging, billing cycle, billing schedule, MetroCluster billing, TMP temporary volumes, Adaptive QoS policy billing, cloned volumes, burst billing 
summary: Facturación de Keystone 
---
= Facturación de Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Keystone permite tarificar precios previsibles y por adelantado para su suscripción de almacenamiento.

Si prefiere el modelo de consumo de gastos operativos (gastos operativos) a gastos de capital o arrendamiento, puede optar por el modelo de pago según crecimiento de Keystone para sus necesidades de consumo flexibles y escalables.

Keystone le ofrece las siguientes instalaciones de facturación:

* Puede pagar según las IOPS y la capacidad comprometida de latencia para satisfacer las necesidades de cargas de trabajo múltiples. Los diferentes niveles de servicio de rendimiento: Extreme, Premium, Standard y Value le permiten gestionar el almacenamiento en función del nivel de servicio que haya adquirido para sus servicios de Keystone.
* Presenta una facturación predecible para la capacidad comprometida y el pago por uso de la capacidad variable (en ráfaga).
* Puede seleccionar un precio de paquete para el hardware, el SO principal y el soporte para un precio de $/TIB. Dispone de una única factura para cada tipo de almacenamiento, archivo, bloque, objeto o servicios de almacenamiento en cloud.
* Seleccione un término flexible para los servicios y el pago: Puede optar por 12 meses, 100 TIB o más por sitio. A partir de entonces puede renovar automáticamente durante 12 meses o ir mes a mes.


La facturación de Keystone se basa en la capacidad comprometida y en el consumo en ráfaga variable.

Para obtener información sobre el uso de la capacidad comprometida y de ráfaga, consulte link:nkfsosm_keystone_service_capacity_definitions.html["Definiciones de la capacidad del servicio de Keystone"].



== Facturación basada en la capacidad comprometida

La capacidad comprometida se refiere a las capacidades de diversos servicios en una única suscripción acordada por las partes involucradas (NetApp/partner y cliente). Esta capacidad se indica en cada pedido de Keystone y se factura, independientemente del consumo real.

.Medición de la capacidad consumida
Como parte de la puesta en marcha del servicio Keystone, NetApp supervisa y mide de forma continua el consumo del servicio. Al menos una vez cada cinco minutos, el sistema genera un registro de consumo, detallando la capacidad consumida actual para la suscripción. Estos registros se agregan a lo largo del período de facturación para generar facturas e informes de uso.



== Facturación basada en consumo en ráfaga

Cuando la capacidad consumida es mayor que la capacidad comprometida para un nivel de servicio determinado, se registra el consumo de ráfaga y se aplican los cargos en consecuencia. Este proceso tiene lugar para cada registro de consumo generado. Por lo tanto, el consumo de ráfaga es un reflejo de la cantidad y tenencia de sus capacidades consumidas en exceso, además de sus capacidades comprometidas.



== Horarios de facturación

Los servicios de Keystone se facturan mensualmente y anualmente.

.Facturación mensual
Las facturas se envían mensualmente. Para el mes en el que se han hecho los servicios, se enviará una factura el mes siguiente. Por ejemplo, la factura de los servicios que ha utilizado en enero se entrega a principios de febrero. Esta factura incluye los cargos por la capacidad comprometida y, si corresponde, cualquier uso de ráfaga.

.Facturación anual
Al principio de cada año de suscripción se genera una factura por el pago mínimo de la capacidad comprometida. Se genera en la fecha de inicio de la suscripción. Al final de un trimestre de suscripción se envía otra factura, en la que se suman los cargos aplicables de cualquier uso de ráfaga acumulado en ese trimestre. Si la capacidad comprometida cambia durante una suscripción, se enviará una factura el mismo día en que el cambio de la capacidad comprometida sea efectivo, por los pagos mínimos prorrateados para el resto de ese año de suscripción.

.Período de gracia en facturación por ráfaga
Durante los primeros 60 días de la activación de una suscripción, se registrará cualquier consumo de bursting que acumule, pero no se cargará en su factura del servicio de Keystone. Este período de gracia le otorga el tiempo necesario para configurar su almacenamiento con la configuración de calidad de servicio adaptable (AQoS) adecuada para poder supervisarlo y facturarlo correctamente. Al configurar el almacenamiento correctamente, puede evitar cargos de ráfaga inesperados. Cualquier uso de ráfaga acumulado después del período de gracia inicial de 60 días se facturará en su próxima factura. Este período de gracia no afecta a ninguna modificación o renovación de sus suscripciones existentes.



== Escenarios varios para la facturación Keystone

Hay varios escenarios para la facturación de Keystone y deberías estar familiarizado con esos escenarios.



=== Facturación de volúmenes clonados

Si los volúmenes se clonan en ONTAP y se los utiliza para realizar un backup y restaurar los datos, puede continuar mediante los clones sin ningún pago adicional. Sin embargo, se cobrarán volúmenes clonados utilizados para cualquier otro fin en el negocio durante un gran período de tiempo.

Tenga en cuenta lo siguiente:

* Los volúmenes clonados no pueden cargarse siempre que su tamaño sea inferior al 10 % del volumen principal (la capacidad física utilizada en el volumen clonado en comparación con la capacidad física utilizada en el volumen principal).
* No hay periodo de gracia de 24 horas para los volúmenes clonados, solo se considera el tamaño del clon.
* Una vez que el volumen clonado supera el 10 % del tamaño físico del volumen principal, el clon se factura como volumen estándar (capacidad utilizada lógica).




=== Facturación de MetroCluster

La protección de datos avanzada utiliza MetroCluster de NetApp para reflejar datos entre dos clústeres separados físicamente. En los agregados duplicados de MetroCluster, los datos se escriben dos veces una en cada clúster. El servicio Keystone cobra por el consumo en cada lado de forma independiente, lo que genera dos registros de consumo idénticos. Si supervisa los clústeres mediante ONTAP System Manager (System Manager) o Active IQ Unified Manager (Unified Manager), es posible que observe una discrepancia entre el consumo notificado en estas herramientas y los servicios de Keystone. System Manager y Unified Manager no notifican volúmenes en un clúster reflejado (remoto); al hacerlo, informa de la mitad de las métricas de consumo que informa el servicio de Keystone.

Por ejemplo: El sitio A y el sitio B se configuran en una configuración de MetroCluster. Cuando un usuario crea un volumen de 10 TB en el sitio A, se crea un volumen idéntico de 10 TB en el sitio B. Keystone distingue los volúmenes y registra un consumo adicional de 10TB MB en cada sitio, lo que supone un aumento total de 20TB TB. System Manager y Unified Manager informan sobre un volumen de 10 TB creado en el sitio A.



=== Facturación de volúmenes temporales

Ocasionalmente, ONTAP crea volúmenes temporales (TMP) al mover volúmenes. Estos volúmenes temporales son de corta duración y el consumo en estos volúmenes no se mide para facturación.



=== Facturación y políticas de calidad de servicio adaptativas

Keystone mide el consumo en función de los niveles de servicio. Cada nivel de servicio está asociado a una política de calidad de servicio (QoS) adaptable específica. Durante la implementación, recibirá un informe de los detalles de cada política de calidad de servicio para los servicios de Keystone que haya suscrito. Durante las operaciones de gestión del almacenamiento, asegúrese de que sus volúmenes tengan asignadas políticas de calidad de servicio adecuadas según sus niveles de servicio suscritos a fin de evitar facturas inesperadas. Para obtener más información sobre las políticas de calidad de servicio en ONTAP, consulte link:https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html["Garantice el rendimiento con información general de calidad de servicio"].



=== Facturación de destinos de SnapMirror

El precio del volumen de destino de SnapMirror determinado por la política de calidad de servicio para el nivel de servicio asignado en el origen. Sin embargo, si el origen no tiene una política de calidad de servicio asociada, el destino se factura en función del nivel de servicio disponible más bajo.



=== Facturación para FlexGroups

Las instancias de FlexGroup se facturan según la política de calidad de servicio adaptativa de FlexGroup. No se consideran las políticas de calidad de servicio de sus componentes.



=== Facturación para LUN

Para las LUN, normalmente se sigue el mismo patrón de facturación que para los volúmenes regulados por las políticas de calidad de servicio. Si se establecen políticas de calidad de servicio independientes en las LUN, realice lo siguiente:

* El tamaño de la LUN se cuenta para su consumo en función del nivel de servicio asociado de esa LUN.
* El resto del espacio del volumen, si lo hay, se cargará según la política de calidad de servicio del nivel de servicio establecido en el volumen.




=== Facturación para el uso de FabricPool

Si los datos se organizan en niveles desde un sistema Keystone hasta el almacenamiento de objetos ONTAP simple Storage Service (S3) o StorageGRID de NetApp, la capacidad consumida en el nivel activo (sistema Keystone) se reducirá en función de la cantidad de datos que se haya organizado en niveles, lo que afectará a la facturación resultante. Esto es independientemente del hecho de que la suscripción a Keystone cubra el almacenamiento ONTAP S3 o los sistemas StorageGRID.

Para organizar sus datos en niveles en un almacenamiento de objetos de terceros, póngase en contacto con su Keystone Success Manager.

Si quiere más información sobre el uso de la tecnología FabricPool en sus suscripciones de Keystone, consulte link:nkfsosm_tiering.html["Organización en niveles"].



=== Facturación para volúmenes raíz y del sistema

Los volúmenes raíz y del sistema se supervisan como parte de la supervisión general del servicio de Keystone, pero no se cuentan o se facturan. El consumo en estos volúmenes está exento de facturación.
