---
sidebar: sidebar 
permalink: nkfsfaq_overview.html 
keywords: netapp, keystone, overview, 
summary: Información general de NetApp Keystone 
---
= Preguntas más frecuentes sobre NetApp Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Las siguientes preguntas proporcionan respuestas a sus consultas frecuentes sobre NetApp Keystone.

* ¿Qué es NetApp Keystone?*

NetApp Keystone es una cartera de alternativas de gastos de capital (capex) en las instalaciones. Para obtener más información, consulte https://www.netapp.com/services/keystone/["NetApp Keystone"].

*¿Cómo beneficia NetApp Keystone a mis clientes?*

NetApp Keystone es un puente que conecta los pilares de nuestra estrategia de gastos de capital y cloud híbrido, y ofrece agilidad, flexibilidad financiera y un riesgo financiero reducido que ayuda a los clientes a satisfacer sus necesidades empresariales y de flujo de caja.

La marca NetApp Keystone ofrece una cartera de soluciones de pago flexibles que incluyen opciones tradicionales de financiación, arrendamiento, y fijas o variables para clientes que tienen un gran peso en efectivo, junto con los servicios Keystone.

*Servicios Keystone (OPEX, experiencia similar a la nube):* * Prefiere un 100 % de gastos operativos, por lo que los activos no terminarán en el balance de tu cliente * Proveedores de servicios internos/externos que busquen alinear los costes con el uso/los ingresos * Cargas de trabajo con un crecimiento de capacidad impredecible * Recursos de TI reasignados a las tareas de almacenamiento típicas (migraciones, actualizaciones técnicas, actualizaciones, Y así sucesivamente) * Solución a corto plazo antes de migrar las cargas de trabajo a la nube * repatriar las cargas de trabajo del cloud a las instalaciones

* ¿Qué es NetApp Keystone?*

NetApp Keystone es un nuevo modelo de adquisición basado en suscripción en las instalaciones y flexible. Permite a los clientes acelerar la rentabilidad de la inversión eliminando los obstáculos a la hora de gestionar los recursos y pasando por el largo ciclo de adquisición. Los servicios Keystone permiten a los clientes alinear la economía con sus prioridades empresariales. Para obtener más información, consulte link:https://docs.netapp.com/us-en/keystone/index.html#netapp-keystone-flex-subscription["aquí"].

* ¿Qué significa en las instalaciones?*

En las instalaciones se define como un centro de datos propiedad del cliente o un espacio propiedad del cliente en una instalación de colocación. El cliente es responsable del espacio, la electricidad y la refrigeración.

*¿Cuáles son los beneficios de los servicios Keystone?*

Algunas de las ventajas de los servicios de Keystone son las siguientes:

* Libera al personal DE TECNOLOGÍA de tareas complicadas relacionadas con el almacenamiento y le permite centrarse en la gestión de aplicaciones
* Reduce la inversión de capital inicial
* Permite a los clientes satisfacer sus demandas sin sobreaprovisionamiento
* Alinea los costes del almacenamiento de datos con las necesidades/actividades del negocio
* Simplifica el aprovisionamiento de infraestructuras evitando los complejos procedimientos de adquisición organizativos
* Mantiene los datos seguros en sus instalaciones
* Permite un control adecuado sobre el cumplimiento, el rendimiento y la seguridad para obtener más información, consulte link:https://docs.netapp.com/us-en/keystone/index.html#benefits-of-flex-subscription["aquí"].

