---
settings:
  name: Keystone
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr,it-it
sidebar:
  entries:
  - title: Servicios NetApp Keystone
    url: "/index.html"
    entries:
    - title: Términos y descripción del servicio
      url: "/nkfsosm_service_terms_and_description_overview.html"
      entries:
      - title: Definiciones de capacidad de servicios
        url: "/nkfsosm_keystone_service_capacity_definitions.html"
      - title: Niveles de servicio en Keystone
        url: "/nkfsosm_performance.html"
      - title: Definiciones y métricas de nivel de servicio
        url: "/nkfsosm_service_level_metrics_and_definitions.html"
      - title: Calidad de servicio adaptativa en Keystone
        url: "/aqos-kfs.html"
      - title: Facturación
        url: "/nkfsosm_kfs_billing.html"
      - title: Protección de datos
        url: "/nkfsosm_data_protection.html"
      - title: Organización en niveles
        url: "/nkfsosm_tiering.html"
      - title: Disco no retornable
        url: "/nkfsosm_nrd.html"
      - title: Soporte de ciudadanos de EE. UU
        url: "/nkfsosm_uscs.html"
      - title: Keystone y Equinix
        url: "/nkfsosm_equinix.html"
    - title: Modelo operativo y responsabilidades
      url: "/nkfsosm_overview.html"
    - title: Soporte para multi-tenancy y multi-tenancy
      url: "/nkfsosm_tenancy_overview.html"
    - title: Infraestructura Keystone
      url: "/nkfsosm_keystone_service_delivery_architecture_overview.html"
    - title: Los requisitos del centro
      url: "/nkfsosm_site_requirements.html"
    - title: Operaciones
      url: "/nkfsosm_netapp_global_services_and_support_center_@gssc@.html"
    - title: Keystone y asesor digital Active IQ
      url: "/nkfsosm-keystone-and-aiq.html"
      entries:
      - title: Ver y generar informes desde el Asesor digital de Active IQ
        url: "/aiq-keystone-details.html"
  - title: Notas de la versión
    entries:
    - title: Novedades
      url: "/rn_whats_new.html"
    - title: Problemas solucionados
      url: "/rn_fixed_issues.html"
    - title: Problemas conocidos
      url: "/rn_known_issues.html"
  - title: Preguntas frecuentes sobre las suscripciones de Keystone
    url: "/nkfsfaq_overview.html"
    entries:
    - title: Suscripciones de Keystone
      url: "/nkfsfaq_keystone_subscription.html"
    - title: Detalles de la oferta de servicios
      url: "/nkfsfaq_service_offer_details.html"
    - title: Modelo operativo
      url: "/nkfsfaq_operating_models.html"
  - title: Avisos legales
    url: "/legal-notices.html"
