---
sidebar: sidebar 
permalink: seapiref_subtenants.html 
keywords: netapp, keystone, subtenants, 
summary: Subinquilinos Keystone 
---
= Subinquilinos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilice los métodos enumerados en la siguiente tabla para recuperar, crear, modificar y eliminar subarrendatarios.

|===
| Método HTTP | Ruta | Descripción 


| `GET` | `/v2.1/subtenants` | Recuperar subinquilinos. 


| `GET` | `/v2.1/subtenants/{id}` | Recuperar un subarrendatario por el identificador de subarrendatario. 


| `POST` | `/v2.1/subtenants`` | Cree un nuevo subarrendatario. 


| `PUT` | `/v2.1/subtenants/{id}` | Modifique los detalles de un subarrendatario. Puede modificar el nombre del subarrendatario. 


| `DELETE` | `/v2.1/subtenants/{id}` | Eliminar un subarrendatario. 
|===


== Atributos de subarrendatario

En la siguiente tabla se enumeran los atributos de subarrendatario.

|===
| Atributo | Tipo | Descripción 


| `id` | Cadena | Identificador único del subarrendatario. 


| `name` | Cadena | El nombre del subarrendatario. 


| `code` | Cadena | Código especificado por el cliente (o predeterminado) que representa al subarrendatario. 


| `tenant_id` | Cadena | El identificador del arrendatario al que pertenece el subarrendatario. 
|===


== Recuperar todos los subinquilinos

Utilice el método que se muestra en la siguiente tabla para recuperar todos los subinquilinos o un subconjunto de todos los subinquilinos. Especificar un `tenant_id` sólo devolverá los subarrendatarios que pertenecen a ese arrendatario.

|===
| Método HTTP | Ruta | Descripción | Parámetros 


| `GET` | `/v2.1/subtenants` | Recuperar subinquilinos. | `tenant_id`: (Opcional) devuelve los subarrendatarios que pertenecen al arrendatario especificado. desplazamiento y límite– consulte 
|===
Atributos de cuerpo de solicitud necesarios: `none`

*Ejemplo de cuerpo de solicitud:*

....
none
....
*Ejemplo de cuerpo de respuesta:*

....
{
  "status": {
    "user_message": "Okay. Returned 2 records.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 2,
    "total_records": 202,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 0,
    "limit": 2,
    "records": [      {
        "id": "5e7c3af8aab46c00014ce878",
        "description": "",
        "name": "MySubtenant",
        "code": "mysubtenant",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant"
      },
      {
        "id": "5d9144f3869caefed0f39f82",
        "description": "",
        "name": "Mysubtenant2",
        "code": "myothersubtenant",
        "tenant_id": "5d914499869caefed0f39eee",
        "tenant": "MyTenant"
      }
    ]
  }
}
....


== Recuperar un subarrendatario por ID

Utilice el método que se muestra a continuación para recuperar un subarrendatario por ID.

|===
| Método HTTP | Ruta | Descripción | Parámetros 


| `GET` | `/v2.1/subtenants/{id}` | Recupere el subarrendatario especificado por el ID. | `id (string)`: El identificador único del subarrendatario. 
|===
Atributos de cuerpo de solicitud necesarios: `none`

*Ejemplo de cuerpo de solicitud:*

....
none
....
*Ejemplo de cuerpo de respuesta:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5e7c3af8aab46c00014ce878",
        "description": "",
        "name": "MySubtenant",
        "code": "subtenantcode",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant"
      }
    ]
  }
}
....


== Cree un subarrendatario

Utilice el método que se muestra en la siguiente tabla para crear un subarrendatario.

|===
| Método HTTP | Ruta | Descripción | Parámetros 


| `POST` | `/v2.1/subtenants` | Cree un nuevo subarrendatario. | Ninguno 
|===
Atributos de cuerpo de solicitud necesarios: `name`, `code`, `tenant_id`

*Ejemplo de cuerpo de solicitud:*

....
{
  "name": "MySubtenant",
  "code": "mynewsubtenant",
  "tenant_id": "5ed5ac802c356a0001a735af"
}
....
*Ejemplo de cuerpo de respuesta:*

....
{
  "status": {
    "user_message": "Okay. New resource created.",
    "verbose_message": "",
    "code": 201
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ecefbbef418b40001f20bd6",
        "description": "",
        "name": "MyNewSubtenant",
        "code": "mynewsubtenant",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant"
      }
    ]
  }
}
....


== Modificar un subarrendatario por ID

Utilice el método que se muestra en la siguiente tabla para modificar un subarrendatario por ID.

|===
| Método HTTP | Ruta | Descripción | Parámetros 


| `PUT` | `/v2.1/subtenants/{id}` | Modifique el subarrendatario especificado por el ID. Puede cambiar el nombre del subarrendatario. | `id (string)`: El identificador único del subarrendatario. 
|===
Atributos de cuerpo de solicitud necesarios: `name`

*Ejemplo de cuerpo de solicitud:*

....
{
  "name": "MyModifiedSubtenant"
}
....
*Ejemplo de cuerpo de respuesta:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ecefbbef418b40001f20bd6",
        "description": "",
        "name": "MyNewSubtenant",
        "code": "mynewsubtenant",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant"
      }
    ]
  }
}
....


== Eliminar un subarrendatario por ID

Utilice el método que se muestra en la siguiente tabla para eliminar un subarrendatario por ID.

|===
| Método HTTP | Ruta | Descripción | Parámetros 


| `DELETE` | `/v2.1/subtenants/{id}` | Elimine el subarrendatario especificado por el ID. | `id (string)`: El identificador único del subarrendatario. 
|===
Atributos de cuerpo de solicitud necesarios: `none`

*Ejemplo de cuerpo de solicitud:*

....
none
....
*Ejemplo de cuerpo de respuesta:*

....
No content for succesful delete
....