---
sidebar: sidebar 
permalink: seapiref_file_services_apis.html 
keywords: netapp, keystone, file services, file servers, file shares, apis 
summary: API de servicios de archivos Keystone 
---
= API de servicios de archivos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede usar las API de servicios de archivos para ver y gestionar los servidores de archivos y los recursos compartidos de archivos.

Antes de crear recursos compartidos de archivos, debe crear servidores de archivos para alojarlos.



== API de servidores de archivos

Puede usar las API de servidores de archivos para ver y gestionar los servidores de archivos. Para obtener más información sobre los servidores de archivos, consulte link:sewebiug_create_a_file_server.html["Cree un servidor de archivos"].

[cols="1,1,3,2"]
|===
| HTTP Verbo | Ruta | Descripción | Parámetros obligatorios/cuerpo de solicitud 


 a| 
`GET`
 a| 
`/v2.1/fileservers`
| Puede recuperar los detalles de todos los servidores de archivos. Recupera detalles de los servidores de archivos, como el ID del servidor de archivos, el nombre, la región, la zona, el inquilino, y etiquetas.  a| 
`offset`: El número de elementos que se deben omitir antes de comenzar a recopilar el conjunto de resultados.
`limit`: Los números de elementos que se van a devolver.



 a| 
`GET`
 a| 
`/v2.1/fileservers/{id}`
| Puede recuperar los detalles de un servidor de archivos específico. Recupera detalles del servidor de archivos, como nombre, región, zona, inquilino, Y etiquetas basadas en el ID introducido.  a| 
`id`: El identificador del servidor de archivos.



 a| 
`POST`
 a| 
`/v2.1/fileservers`
| Puede crear un servidor de archivos. Agregue los valores del cuerpo de solicitud para crear un servidor de archivos con los parámetros especificados, como nombre, ID de subinquilino, zona e ID de subred.  a| 
`name`: El nombre del servidor de archivos.
`subtenant_id`: El código del subinquilino.
`zone`: El nombre de la zona.
`subnet_id`: El código de la subred.



 a| 
`POST`
 a| 
`/v2.1/fileservers/{id}/`
`tags`
| Puede crear o reemplazar etiquetas de un servidor de archivos. Agregue el ID del servidor de archivos y los valores de las etiquetas en el formato "par clave:valor" del cuerpo de la solicitud.  a| 
`id`: El identificador del servidor de archivos.



 a| 
`PUT`
 a| 
`/v2.1/fileservers/{id}`
| Puede modificar cualquier servidor de archivos basándose en su ID. Agregue el ID del servidor de archivos y los valores que desea modificar en el cuerpo de la solicitud, como el nombre, el protocolo, la zona, la región y las etiquetas.  a| 
`id`: El identificador del servidor de archivos.



 a| 
`DELETE`
 a| 
`/v2.1/fileservers/{id}`
 a| 
Puede eliminar cualquier servidor de archivos por su ID.
 a| 
`id`: El identificador del servidor de archivos.

|===
[NOTE]
====
Antes de eliminar un servidor de archivos, debe eliminar todos los recursos compartidos de archivos asignados a él.

Después de eliminar los servidores de archivos habilitados para CIFS, el objeto de equipo de Active Directory permanece. Solicite al administrador de Active Directory que elimine manualmente el objeto de equipo del servidor de archivos eliminado de Active Directory.

====


== API de recursos compartidos de archivos

Puede utilizar las API de uso compartido de archivos para ver y gestionar los recursos compartidos de archivos. Para obtener más información sobre los recursos compartidos de archivos, consulte link:sewebiug_create_a_new_file_share.html["Cree un recurso compartido de archivos"].

[cols="1,1,3,2"]
|===
| HTTP Verbo | Ruta | Descripción | Parámetros obligatorios/cuerpo de solicitud 


 a| 
`GET`
 a| 
`/v2.1/fileshares`
| Puede recuperar los detalles de todos los recursos compartidos de archivos. Recupera detalles de los archivos compartidos, como ID, nombre, política de instantáneas, protocolos, IP del servidor de archivos y etiquetas.  a| 
`offset`: El número de elementos que se deben omitir antes de comenzar a recopilar el conjunto de resultados.
`limit`: Los números de elementos que se van a devolver.



 a| 
`GET`
 a| 
`/v2.1/fileshares/{id}`
| Puede recuperar los detalles de un recurso compartido de archivos específico. Recupera detalles del recurso compartido de archivos, como ID, nombre, política de instantáneas, protocolos, IP del servidor de archivos, Y etiquetas basadas en el ID introducido.  a| 
`id`: El ID del recurso compartido de archivos.



 a| 
`POST`
 a| 
`/v2.1/fileshares`
| Puede crear un recurso compartido de archivos. Agregue los valores del cuerpo de la solicitud para crear un recurso compartido de archivos con los parámetros especificados, como ID, nombre, política de instantáneas, protocolos, IP del servidor de archivos y etiquetas.  a| 
`name`: El nombre del recurso compartido de archivos.
`share_path`: La ruta de acceso del recurso compartido de archivos.
`fileserver_id`: El identificador del servidor de archivos.
`size_gb`: El tamaño del recurso compartido de archivos en GIBS.
`service_level`: El nombre de nivel de servicio aplicable: Standard, Premium, Premium-Tiering, Extreme o Extreme-Tiering.
`protocol`: El protocolo utilizado para acceder al recurso compartido de archivos (NFS, CIFS o multiprotocolo).
`security_style`: El estilo de seguridad (Unix o NTFS).
`export_policy`: La política de exportación del recurso compartido de archivos.



 a| 
`POST`
 a| 
`/v2.1/fileshares/{id}/`
`snapshot/{name}`
| Puede crear una instantánea de un recurso compartido de archivos.  a| 
`id`: El ID del recurso compartido de archivos.
`name`: El nombre de la instantánea.



 a| 
`POST`
 a| 
`/v2.1/fileshares/{id}/`
`tags`
| Puede crear o reemplazar etiquetas para un recurso compartido de archivos. Agregue el ID del recurso compartido de archivos y los valores de las etiquetas en el formato "par clave:valor" del cuerpo de la solicitud.  a| 
`id`: El ID del recurso compartido de archivos.



 a| 
`PUT`
 a| 
`/v2.1/fileshares/{id}`
| Puede modificar cualquier recurso compartido de archivos en función de su ID. Agregue el ID del servidor de archivos y los valores que desea modificar en el cuerpo de la solicitud, como el nombre, el protocolo, la política de instantáneas, la política de copia de seguridad y las etiquetas.  a| 
`id`: El ID del recurso compartido de archivos.
`name`: El nombre del recurso compartido de archivos.
`size_gb`: El tamaño del recurso compartido de archivos en GIBS.
`service_level`: El nombre de nivel de servicio aplicable: Standard, Premium, Premium-Tiering, Extreme o Extreme-Tiering.
`protocol`: El protocolo utilizado para acceder al recurso compartido de archivos (NFS, CIFS o multiprotocolo).
`export_policy`: La política de exportación del recurso compartido de archivos.



 a| 
`DELETE`
 a| 
`/v2.1/fileshares/{id}`
| Puede eliminar cualquier recurso compartido de archivos por su ID.  a| 
`id`: El ID del recurso compartido de archivos.



 a| 
`DELETE`
 a| 
`/v2.1/fileshares/{id}/`
`snapshot/{name}`
| Se puede eliminar cualquier instantánea de un recurso compartido de archivos mediante el ID del recurso compartido de archivos y el nombre de la instantánea.  a| 
`id`: El ID del recurso compartido de archivos.
`name`: El nombre de la instantánea.

|===

NOTE: Para recursos compartidos de CIFS, añadir una `$` el carácter al final de la ruta de acceso compartido lo hará un recurso compartido oculto, por ejemplo, `pathtomyhiddenshare$`.
