---
sidebar: sidebar 
permalink: seapiref_service_requests.html 
keywords: netapp, keystone, service, requests, 
summary: Solicitudes de servicio de Keystone 
---
= Solicitudes de servicio
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilice los métodos enumerados en la siguiente tabla para crear y recuperar solicitudes de servicio.

|===


| Método HTTP | Ruta | Descripción 


| `GET` | `/v2.1/tenants/{tenant_id}/servicerequests` | Recuperar peticiones de servicio. 


| `GET` | `/v2.1/tenants/{tenant_id}/servicerequests/{id}` | Recuperar una solicitud de servicio por ID. 


| `POST` | `/v2.1/tenants/{tenant_id}/servicerequests/` | Crear una solicitud de servicio. 


| `GET` | `/v2.1/tenants/{tenant_id}/servicerequests/categories` | Recuperar categorías de solicitud de servicio. 
|===


== Atributos de solicitud de servicio

En la siguiente tabla se enumeran los atributos de solicitud de servicio.

|===


| Atributo | Tipo | Descripción 


| `Id` | Cadena | Un identificador de la solicitud de servicio. Por ejemplo: `SRQ0035952014.` 


| `subject` | Cadena | El objeto de la solicitud de servicio. 


| `comment` | Cadena | Un comentario sobre la solicitud de servicio 


| `category` | Cadena | Categoría de la solicitud: Backup, recuperación ante desastres, técnico, otro o suscripción. 


| `priority` | Cadena | La prioridad de la solicitud de servicio es muy baja, baja, normal, alta o urgente. 


| `subscription` | Cadena | El número de suscripción de Zuora. 


| `commitment` | –  a| 
Detalles de compromisos de suscripción, incluidos:

* Nivel de servicio (cadena): Nivel de servicio: Estándar, Premium o Extreme.
* New_comment (entero): Se requiere capacidad total nueva.




| `zone` | Cadena | El nombre de la zona. 


| `subtenant_id` | Cadena | El identificador de subarrendatario. 


| `storage_object_type` | Cadena | Tipo de objeto de almacenamiento: Servidor de archivos o almacén de bloques. 


| `storage_object_id` | Cadena | El identificador del objeto de almacenamiento. Por ejemplo:
`5d2fb0fb4f47df00015274e3` 


| `service_type` | Cadena | El tipo de servicio: Servicios de archivos, almacenamiento basado en bloques o almacenamiento de objetos. 
|===


== Recuperar peticiones de servicio

Utilice el método que se muestra en la siguiente tabla para recuperar las categorías de solicitud de servicio para el arrendatario especificado.

|===


| Método HTTP | Ruta | Descripción | Parámetros 


| `GET`` | `/v2.1/tenants/{tenant_id}/servicerequests` | Recuperar peticiones de servicio. | `tenant_id`: (Opcional) devuelve las solicitudes de servicio para el arrendatario especificado.
`offset` y.. `limit`– consulte link:seapiref_netapp_service_engine_rest_apis.html#pagination>["Paginación común"] 
|===
Atributos de cuerpo de solicitud necesarios: `none`

*Ejemplo de cuerpo de solicitud:*

....
none
....
*Ejemplo de cuerpo de respuesta:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "total_records": 34,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 6,
    "limit": 1,
    "records": [
      {
        "id": "SRQ0035952014",
        "subject": "DR Failover - fileserver",
        "description": "catgory:Disaster Recovery Failover \n   subtenant: DefaultSubtenants2 \n  region: au-east2 \n zone: au-east2-a \n   fileserver: Demotsysserv1 \n tenant:MyOrg \n comments:comments",
        "priority": "Urgent",
        "status": "New",
        "createdDate": "2020-05-22T04:23:12+0000",
        "updatedDate": "2020-05-22T04:23:12+0000"
      }
    ]
  }
}
....


== Recuperar una solicitud de servicio por ID

Utilice el método indicado en la siguiente tabla para recuperar una solicitud de servicio por ID de solicitud de servicio.

|===


| Método HTTP | Ruta | Descripción | Parámetros 


| `GET` | `/v2.1/tenants/{tenant_id}/servicerequests/{id}` | Recuperar una solicitud de servicio por ID.  a| 
* `tenant_id`: ID de inquilino
* `id`: Petición de servicio IDpor ejemplo: SRQ0035952014


|===
Atributos de cuerpo de solicitud necesarios: `none`

*Ejemplo de cuerpo de solicitud:*

....
none
....
*Ejemplo de cuerpo de respuesta:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "SRQ0035952014",
        "subject": "DR Failover - fileserver",
        "description": "catgory:Disaster Recovery Failover \n   subtenant: DefaultSubtenants2 \n  region: au-east2 \n zone: au-east2-a \n   fileserver: Demotsysserv1 \n tenant:MyOrg \n comments:comments",
        "priority": "Urgent",
        "status": "New",
        "createdDate": "2020-05-22T04:23:12+0000",
        "updatedDate": "2020-05-22T04:23:12+0000"
      }
    ]
  }
}
....


== Crear una solicitud de servicio

Utilice el método indicado en la siguiente tabla para crear una solicitud de servicio.

|===


| Método HTTP | Ruta | Descripción | Parámetros 


| `POST` | `/v2.1/tenants/{tenant_id}/servicerequests/categories` | Crear una solicitud de servicio. | `tenant_id`: El identificador de arrendatario. 
|===
Atributos de cuerpo de solicitud requeridos: Los atributos requeridos dependen de la categoría de solicitud de servicio. En la siguiente tabla se enumeran los atributos del cuerpo de la solicitud.

|===


| Categoría | Obligatorio 


| Suscripción | `subscription` y.. `commitment` 


| Recuperación tras siniestros | `storage_object_type`, `subtenant_id`, y. `storage_object_id` 


| Información técnica | `subtenant_id` y.. `service_type`Si `service_type` es necesario disponer de servicios de archivos o almacenamiento en bloques. 


| Otros | Zona 
|===
*Ejemplo de cuerpo de solicitud:*

....
{
  "subject": "string",
  "comment": "string",
  "category": "subscription",
  "priority": "Normal",
  "subscription": "A-S00003969",
  "commitment": {
    "service_level": "standard",
    "new_commitment": 10
  },
  "zone": "au-east1-a",
  "subtenant_id": "5d2fb0fb4f47df00015274e3",
  "storage_object_type": "fileserver",
  "storage_object_id": "5d2fb0fb4f47df00015274e3",
  "service_type": "File Services"
}
....
*Ejemplo de cuerpo de respuesta:*

....
{
  "status": {
    "user_message": "string",
    "verbose_message": "string",
    "code": "string"
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "string",
        "subject": "string",
        "description": "string",
        "status": "New",
        "priority": "Normal",
        "createdDate": "2020-05-12T03:18:25+0000",
        "UpdatedDate": "2020-05-12T03:18:25+0000"
      }
    ]
  }
....


== Recuperar categorías de solicitud de servicio

En la tabla siguiente se enumeran las categorías de solicitud de servicio de recuperación para un arrendatario especificado.

|===


| Método HTTP | Ruta | Descripción | Parámetros 


| `GET` | `/v2.1/tenants/{tenant_id}/servicerequests/categories` | Recuperar categorías de peticiones de servicio. | `tenant_id:` (Opcional) devuelve las solicitudes de servicio para un arrendatario especificado. 
|===
Atributos de cuerpo de solicitud necesarios: `none`

*Ejemplo de cuerpo de solicitud:*

....
none
....
*Ejemplo de cuerpo de respuesta:*

....
{
  "status": {
    "user_message": "Okay. Returned 5 records.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 5,
    "records": [
      {
        "key": "dr",
        "value": "Disaster Recovery Failover"
      },
      {
        "key": "technical",
        "value": "Technical Issue"
      },
      {
        "key": "other",
        "value": "Other"
      },
      {
        "key": "subscription",
        "value": "Subscription Management"
      },
      {
        "key": "backup",
        "value": "Backup Restore"
      }
    ]
  }
}
....