---
sidebar: sidebar 
permalink: seapiref_service_levels.html 
keywords: netapp, keystone, service, levels, 
summary: Niveles de servicio de Keystone 
---
= Niveles de servicio
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilice los métodos enumerados en la siguiente tabla para recuperar, crear, modificar y eliminar niveles de servicio.

|===
| Método HTTP | Ruta | Descripción 


| `GET` | `/v2.1/servicelevels` | Recupere todos los niveles de servicio. 


| `GET` | `/v2.1/servicelevels/{id}` | Recuperar un nivel de servicio por ID. 


| `POST` | `/v2.1/servicelevels` | Crear un nuevo nivel de servicio. 


| `PUT` | `/v2.1/servicelevels/{id}` | Modifique los detalles del nivel de servicio por ID. 


| `DELETE` | `/v2.1/servicelevels/{id}` | Eliminar un nivel de servicio. 
|===


== Atributos del nivel de servicio

En la siguiente tabla se enumeran los atributos del nivel de servicio.

|===
| Atributo | Tipo | Descripción 


| `id` | Cadena | Identificador único para el nivel de servicio. 


| `name` | Cadena | El nombre del nivel de servicio. 


| `description` | Cadena | La descripción del nivel de servicio. 


| `policy_name` | Cadena | Nombre de calidad de servicio (QoS) de nivel de servicio. Valores permitidos: nse_Value, nse_Standard, nse_Performance y nse_Extreme. 


| `available` | Booleano | Indica si el nivel de servicio está disponible para su uso. 


| `grandfathered` | Booleano | Indica si el nivel de servicio se ha retirado. 


| `peak_iops_per_tb` | Entero | El número máximo de IOPS posible por TIB. 


| `expected_iops_per_tb` | Entero | El número mínimo esperado de IOPS por TIB. 


| `absolute_min_iops` | Entero | El valor mínimo absoluto de IOPS que se utiliza como anulación cuando el número de IOPS esperado es inferior a este valor. 


| `peak_iops_allocation` | Cadena | La asignación de IOPS máxima. Valores permitidos: Asignado_espacio y espacio_utilizado. 


| `io_block_size_kb` | Entero | El tamaño de bloque de I/o (KiB). 


| `min_size_gb` | Entero | El tamaño mínimo (GIB). 


| `max_size_gb` | Entero | El tamaño máximo (GIB). 


| `max_peak_iops` | Entero | La tasa máxima de IOPS máxima para el nivel de servicio. 


| `max_expected_iops` | Entero | El número máximo esperado de IOPS. 


| `autogrow_max_percent` | Entero | El porcentaje máximo de crecimiento automático. 


| `ontap_aggregates` | –  a| 
La lista de agregados de ONTAP. Un agregado de ONTAP consta de:

* `cluster_UIID: ONTAP cluster UUID`
* `aggr_name: ONTAP aggregate name`
* `aggr_uuid: ONTAP aggregate UUID`
* `node_name: ONTAP cluster node name`Por ejemplo:


[listing]
----
"ontap_aggregates": [
    {
      "cluster_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "aggr_name": "string",
      "aggr_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "node_name": "node01"
    }
  ]
----


| `primary_volume_defaults` | –  a| 
* Snapshot_auto_delete_target_free_space (integer): Esta opción especifica el porcentaje de espacio libre en el que debe detenerse la eliminación automática de copias Snapshot.
* auto_size_mode (string): El modo autosize del volumen. Valores permitidos: OFF, grow, grow_shrink por ejemplo:


[listing]
----
"primary_volume_defaults": {    "snapshot_auto_delete_target_free_space": 3,    "auto_size_mode": "grow_shrink"
----
|===


== Recuperar los niveles de servicio

Utilice el método indicado en la siguiente tabla para recuperar todos los niveles de servicio.

|===
| Método HTTP | Ruta | Descripción | Parámetros 


| `GET` | `/v2.1/servicelevels` | Recupere todos los niveles de servicio. | Ninguno 
|===
Atributos de cuerpo de solicitud necesarios: `none`

*Ejemplo de cuerpo de solicitud:*

....
none
....
*Ejemplo de cuerpo de respuesta:*

....
{
  "status": {
    "user_message": "Okay. Returned 3 records.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 3,
    "records": [
      {
        "name": "standard",
        "description": "Best suited for general purpose workloads",
        "slo": "1000IOPS/TB",
        "min_size": 137438953472,
        "io_block_size_kb": 32,
        "min_size_gb": 10,
        "max_size_gb": 40960,
        "min_iops": 100,
        "peak_iops_per_tb": 1000,
        "expected_iops_per_tb": 700,
        "max_peak_iops": 40000,
        "max_expected_iops": 28000,
        "max_peak_throughput": 1250,
        "max_expected_throughput": 875
      },
      {
        "name": "extreme",
        "description": "Best suited for performance-critical workloads",
        "slo": "12000IOPS/TB",
        "min_size": 91625968981,
        "io_block_size_kb": 32,
        "min_size_gb": 10,
        "max_size_gb": 10240,
        "min_iops": 500,
        "peak_iops_per_tb": 12000,
        "expected_iops_per_tb": 8000,
        "max_peak_iops": 120000,
        "max_expected_iops": 60000,
        "max_peak_throughput": 3750,
        "max_expected_throughput": 1875
      },
      {
        "name": "premium",
        "description": "Best suited for databases and high performance workloads",
        "slo": "4000IOPS/TB",
        "min_size": 137438953472,
        "io_block_size_kb": 32,
        "min_size_gb": 10,
        "max_size_gb": 10240,
        "min_iops": 300,
        "peak_iops_per_tb": 4000,
        "expected_iops_per_tb": 3000,
        "max_peak_iops": 40000,
        "max_expected_iops": 30000,
        "max_peak_throughput": 1250,
        "max_expected_throughput": 937
      }
    ]
  }
}
....


== Recuperar niveles de servicio por nombre

Utilice el método que se indica en la siguiente tabla para recuperar los niveles de servicio por nombre.

|===
| Método HTTP | Ruta | Descripción | Parámetros 


| `GET` | `/v2.1/servicelevels/{name}` | Recuperar un nivel de servicio por nombre. | `name (string)`: El nombre del nivel de servicio. 
|===
Atributos de cuerpo de solicitud necesarios: `none`

*Ejemplo de cuerpo de solicitud:*

....
none
....
*Ejemplo de cuerpo de respuesta:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "name": "premium",
        "description": "Best suited for databases and high performance workloads",
        "slo": "4096IOPS/TB",
        "min_size": 137438953472,
        "io_block_size_kb": 32,
        "min_size_gb": 10,
        "max_size_gb": 10240,
        "min_iops": 300,
        "peak_iops_per_tb": 4096,
        "expected_iops_per_tb": 3000,
        "max_peak_iops": 40000,
        "max_expected_iops": 30000,
        "max_peak_throughput": 1250,
        "max_expected_throughput": 937
      }
    ]
  }
}
....


== Crear un nivel de servicio

Utilice el método indicado en la siguiente tabla para crear un nivel de servicio.

|===
| Método HTTP | Ruta | Descripción | Parámetros 


| `POST` | `/v2.1/servicelevels` | Crear un nivel de servicio. | Ninguno 
|===
Atributos de cuerpo de solicitud necesarios: `name`, `policy_name`

*Ejemplo de cuerpo de solicitud:*

....
{
  "name": "MyServiceLevelName",
  "description": "My new service level description",
  "policy_name": "nse_value",
  "available": true,
  "grandfathered": false,
  "peak_iops_per_tb": 1000,
  "expected_iops_per_tb": 700,
  "absolute_min_iops": 100,
  "peak_iops_allocation": "allocated_space",
  "io_block_size_kb": 32,
  "min_size_gb": 10,
  "max_size_gb": 40960,
  "max_peak_iops": 20000,
  "max_expected_iops": 5000,
  "autogrow_max_percent": 3,
  "ontap_aggregates": [
    {
      "cluster_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "aggr_name": "string",
      "aggr_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "node_name": "node01"
    }
  ],
  "primary_volume_defaults": {
    "snapshot_auto_delete_target_free_space": 3,
    "auto_size_mode": "grow_shrink"
  }
}
....
*Ejemplo de cuerpo de respuesta:*

....
{
  "status": {
    "user_message": "Okay. New resource created.",
    "verbose_message": "",
    "code": 201
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "name": "MyServiceLevelName",
        "description": "My new service level description",
        "slo": "1000IOPS/TB",
        "min_size": 0,
        "io_block_size_kb": 32,
        "min_size_gb": 10,
        "max_size_gb": 40960,
        "min_iops": 100,
        "peak_iops_per_tb": 1000,
        "expected_iops_per_tb": 700,
        "max_peak_iops": 20000,
        "max_expected_iops": 5000,
        "max_peak_throughput": 625,
        "max_expected_throughput": 156
      }
    ]
  }
}
....


== Modificar un nivel de servicio

Utilice el método que se indica en la siguiente tabla para modificar un nivel de servicio.

|===
| Método HTTP | Ruta | Descripción | Parámetros 


| `PUT` | `/v2.1/servicelevels/{name}` | Modifique los detalles de un nivel de servicio. | `name (string)`: El nombre del nivel de servicio. 
|===
Atributos de cuerpo de solicitud necesarios: `none`

*Ejemplo de cuerpo de solicitud:*

....
{
  "name": "MyNewServiceLevelName",
  "description": "Service level description",
  "policy_name": "nse_value",
  "available": false,
  "grandfathered": false,
  "peak_iops_per_tb": 1000,
  "expected_iops_per_tb": 700,
  "absolute_min_iops": 100,
  "peak_iops_allocation": "allocated_space",
  "io_block_size_kb": 32,
  "min_size_gb": 10,
  "max_size_gb": 40960,
  "max_peak_iops": 20000,
  "max_expected_iops": 5000,
  "autogrow_max_percent": 3,
  "ontap_aggregates": [
    {
      "cluster_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "aggr_name": "string",
      "aggr_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "node_name": "node01"
    }
  ],
  "primary_volume_defaults": {
    "snapshot_auto_delete_target_free_space": 3,
    "auto_size_mode": "grow_shrink"
  }
}
....
*Ejemplo de cuerpo de respuesta:*

....
TBA
....


== Eliminar nivel de servicio por ID

Utilice el método que se muestra en la siguiente tabla para eliminar un nivel de servicio por ID.

|===
| Método HTTP | Ruta | Descripción | Parámetros 


| `DELETE` | `/v2.1/servicelevels/{name}` | Eliminar el nivel de servicio identificado por ID. | `name (string)`: El nombre del nivel de servicio. 
|===
*Ejemplo de cuerpo de solicitud:*

....
none
....
*Ejemplo de cuerpo de respuesta:*

....
No content for succesful delete
....