---
sidebar: sidebar 
permalink: seapiref_block_storage_apis.html 
keywords: netapp, keystone, block storage, block stores, disks, host groups, initiators, apis 
summary: API de almacenamiento basado en bloques de Keystone 
---
= API de almacenamiento basado en bloques
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Es posible usar las API de almacenamiento basado en bloques para ver y gestionar el almacenamiento basado en bloques.

Antes de crear discos, debe crear almacenes de bloques. Cuando se crea un disco, es necesario crear un grupo de hosts o seleccionar un grupo de hosts existente para acceder al disco. Para obtener más información, consulte link:sewebiug_working_with_block_storage_overview.html["Trabajar con el almacenamiento basado en bloques"].



== Almacenes de bloques

Puede utilizar las API de Block Store para recuperar y gestionar los almacenes de bloques.

[cols="1,1,3,2"]
|===
| HTTP Verbo | Ruta | Descripción | Parámetros obligatorios/cuerpo de solicitud 


 a| 
`GET`
 a| 
`/v2.1/blockstores`
| Puede recuperar los detalles de todos los almacenes de bloques. Recupera detalles de los almacenes de bloques, como el identificador de almacén de bloques, la dirección IP, la región, la zona, el ID de subred, y etiquetas.  a| 
`offset`: El número de elementos que se deben omitir antes de comenzar a recopilar el conjunto de resultados.
`limit`: Los números de elementos que se van a devolver.



 a| 
`GET`
 a| 
`/v2.1/blockstores/{id}`
| Puede recuperar los detalles de un almacén de bloques específico. Recupera detalles del almacén de bloques, como la dirección IP, la región, la zona, el ID de subred y las etiquetas basadas en el ID introducido.  a| 
`id`: El ID del almacén de bloques.



 a| 
`POST`
 a| 
`/v2.1/blockstores`
| Puede crear un almacén de bloques. Agregue los valores del cuerpo de solicitud para crear un almacén de bloques con los parámetros especificados, como el protocolo de servicio, el ID de subinquilino, la zona, el ID de subred y las etiquetas.  a| 
`subtenant_id`: El código del subinquilino.
`zone`: El nombre de la zona.
`subnet_id`: El código de la subred.



 a| 
`POST`
 a| 
`/v2.1/blockstores/{id}/`
`tags`
| Puede crear o reemplazar etiquetas para un almacén de bloques. Agregue el ID del almacén de bloques y los valores de las etiquetas en el formato "par clave:valor" del cuerpo de la solicitud.  a| 
`id`: El ID del almacén de bloques.



 a| 
`PUT`
 a| 
`/v2.1/blockstores/{id}`
| Puede modificar cualquier almacén de bloques basándose en su ID. Agregue el ID del almacén de bloques y los valores que desea modificar en el cuerpo de la solicitud, como la zona, el protocolo de servicio y las etiquetas.  a| 
`id`: El ID del almacén de bloques.



 a| 
`DELETE`
 a| 
`/v2.1/blockstores/{id}`
 a| 
Puede eliminar cualquier almacén de bloques por su ID.
 a| 
`id`: El ID del almacén de bloques.

|===

NOTE: Antes de eliminar un almacén de bloques, debe eliminar todos los discos asignados a él.



== Discos

Puede usar las API de discos para recuperar y gestionar los discos.

[cols="1,1,3,2"]
|===
| HTTP Verbo | Ruta | Descripción | Parámetros obligatorios/cuerpo de solicitud 


 a| 
`GET`
 a| 
`/v2.1/disks`
| Puede recuperar los detalles de todos los discos. Recupera detalles de los discos, como el ID de almacén de bloques, el nombre, la ruta de disco, el protocolo, la política de instantáneas, y etiquetas.  a| 
`offset`: El número de elementos que se deben omitir antes de comenzar a recopilar el conjunto de resultados.
`limit`: Los números de elementos que se van a devolver.



 a| 
`GET`
 a| 
`/v2.1/disks/{id}`
| Es posible recuperar los detalles de un disco específico. Recupera detalles del disco, como el ID de almacén de bloque, el nombre, la ruta de disco, el protocolo, la política de instantáneas, Y etiquetas basadas en el ID introducido.  a| 
`id`: El ID del disco.



 a| 
`POST`
 a| 
`/v2.1/disks`
| Es posible crear un disco. Agregue los valores del cuerpo de la solicitud para crear un disco con los parámetros especificados, como el ID de subinquilino, la zona, el nombre, la ruta de acceso al disco, la política de instantáneas, política de backup y etiquetas.  a| 
`subtenant_id`: El código del subinquilino.
`zone`: El nombre de la zona.
`name`: El nombre del disco.
`disk_path`: La ruta del disco.
`protocol`: El protocolo de almacenamiento utilizado para bloquear el acceso al dispositivo.
`os_type`: El tipo de sistema operativo host.
`hostgroup_mappings`: Las asignaciones del grupo de hosts.
`service_level`: El nombre de nivel de servicio aplicable: Standard, Premium, Premium-Tiering, Extreme o Extreme-Tiering.
`size_gb`: El tamaño del disco en gibs.



 a| 
`POST`
 a| 
`/v2.1/disks/{id}/`
`snapshot/{name}`
| Es posible crear una instantánea de un disco.  a| 
`id`: El ID del disco.
`name`: El nombre de la instantánea.



 a| 
`POST`
 a| 
`/v2.1/disks/{id}/`
`tags`
| Puede crear o reemplazar etiquetas de un disco. Agregue el ID del disco y los valores de las etiquetas en el formato "par clave:valor" del cuerpo de la solicitud.  a| 
`id`: El ID del disco.



 a| 
`PUT`
 a| 
`/v2.1/disks/{id}`
| Puede modificar cualquier disco en función de su ID. Añada el ID del disco y los valores que desea modificar en el cuerpo de la solicitud, como el nombre, el nivel de servicio, la política de Snapshot, la política de backup y las etiquetas.  a| 
`id`: El ID del disco.
`hostgroup_mappings`: Las asignaciones del grupo de hosts.



 a| 
`DELETE`
 a| 
`/v2.1/disks/{id}`
| Puede eliminar cualquier disco por su ID.  a| 
`id`: El ID del disco.



 a| 
`DELETE`
 a| 
`/v2.1/disks/{id}/`
`snapshot/{name}`
| Se puede eliminar cualquier instantánea de un disco por el ID del disco y el nombre de la instantánea.  a| 
`id`: El ID del disco.
`name`: El nombre de la instantánea.

|===


== Grupos de hosts

El control de acceso a los discos se gestiona con grupos de hosts. Es posible recuperar y gestionar grupos de hosts con las API de grupos de hosts.

[cols="1,1,3,2"]
|===
| HTTP Verbo | Ruta | Descripción | Parámetros obligatorios/cuerpo de solicitud 


 a| 
`GET`
 a| 
`/v2.1/hostgroups`
| Es posible recuperar los detalles de todos los grupos de hosts. Recupera los detalles de los grupos de hosts, como el nombre, los detalles del subinquilino, los detalles del inquilino, la zona, protocolo, iniciadores, discos que utilizan el grupo de hosts y etiquetas.  a| 
`offset`: El número de elementos que se deben omitir antes de comenzar a recopilar el conjunto de resultados.
`limit`: Los números de elementos que se van a devolver.



 a| 
`GET`
 a| 
`/v2.1/hostgroups/{id}`
| Es posible recuperar los detalles de un grupo de hosts específico. Recupera los detalles del grupo de hosts, como el nombre, los detalles del subinquilino, los detalles del inquilino, la zona, protocolo, iniciadores, discos con los grupos de hosts y etiquetas basadas en el ID introducido.  a| 
`id`: El ID del grupo host.



 a| 
`POST`
 a| 
`/v2.1/hostgroups`
| Es posible crear un grupo de hosts. Agregue los valores del cuerpo de solicitud para crear un grupo de hosts con los parámetros especificados, como nombre, ID de subinquilino, zona, protocolo, iniciadores y etiquetas.  a| 
`name`: El nombre del grupo host.
`subtenant_id`: El código del subinquilino.
`zone`: El nombre de la zona.
`protocol`: El protocolo de almacenamiento utilizado para bloquear el acceso al dispositivo.
`os_type`: El tipo de sistema operativo host.



 a| 
`POST`
 a| 
`/v2.1/hostgroups/{id}/`
`tags`
| Es posible crear o reemplazar etiquetas para un grupo de hosts. Agregue el ID del grupo de hosts y los valores de las etiquetas en el formato "par clave:valor" del cuerpo de la solicitud.  a| 
`id`: El ID del grupo host.



 a| 
`DELETE`
 a| 
`/v2.1/hostgroups/{id}`
| Puede eliminar cualquier grupo de hosts según su ID.  a| 
`id`: El ID del grupo host.

|===


== Iniciadores de un grupo de hosts

Puede usar la API de grupos de hosts para recuperar y gestionar los iniciadores asignados a los grupos de hosts.

[cols="1,1,3,2"]
|===
| HTTP Verbo | Ruta | Descripción | Parámetros obligatorios/cuerpo de solicitud 


 a| 
`GET`
 a| 
`/v2.1/hostgroups/{id}/`
`initiators`
| Puede recuperar los detalles de todos los iniciadores. Recupera los iniciadores y sus alias.  a| 
`id`: El ID del grupo host.



 a| 
`GET`
 a| 
`/v2.1/hostgroups/{id}/`
`initiators/{alias}`
| Puede recuperar los detalles de un iniciador específico. Recupera el iniciador según el ID y el alias introducidos.  a| 
`id`: El ID del grupo host.
`alias`: El nombre de alias del iniciador.



 a| 
`POST`
 a| 
`/v2.1/hostgroups/{id}/`
`initiators`
 a| 
Es posible crear un iniciador para un grupo de hosts. Añada los valores del iniciador y su alias en el cuerpo de la solicitud para crear un iniciador para el grupo de hosts.
 a| 
`id`: El ID del grupo host.
`alias`: El nombre de alias del iniciador.
`initiator`: El iniciador (nombres completos de iSCSI o WWPN de FC).



 a| 
`PATCH`
 a| 
`/v2.1/hostgroups/{id}/`
`initiators/{alias}`
| Puede modificar un iniciador. Añada el nuevo iniciador en el cuerpo de la solicitud.  a| 
`id`: El ID del grupo host.
`alias`: El nombre de alias del iniciador.
`initiator`: El iniciador (nombres cualificados de iSCSI o WWPN de FC).'



 a| 
`DELETE`
 a| 
`/v2.1/hostgroups/{id}/`
`initiators/{alias}`
 a| 
Es posible eliminar un iniciador según el ID del grupo de hosts y el alias del iniciador.
 a| 
`id`: El ID del grupo host.
`alias`: El nombre de alias del iniciador.

|===
[NOTE]
====
Al añadir un iniciador a un grupo de hosts, el iniciador debe coincidir con el protocolo del grupo de hosts. Se deben usar IQN para los grupos de hosts con el protocolo iSCSI y WWPN para los grupos de hosts con el protocolo FC.

La eliminación de un iniciador de un grupo de hosts afecta a todos los discos a los que está asignado el grupo de hosts.

====