---
sidebar: sidebar 
permalink: seapiref_object_storage_apis.html 
keywords: netapp, keystone, object, storage, apis, 
summary: API de almacenamiento de objetos de Keystone 
---
= API de almacenamiento de objetos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
En esta sección se proporcionan las API para gestionar el almacenamiento de objetos, los usuarios de almacenamiento de objetos y el grupo de almacenamiento de objetos.

El flujo de trabajo de almacenamiento de objetos incluye las siguientes tareas:

* Cree una cuenta de almacenamiento de objetos.
* Cree un grupo de almacenamiento de objetos.
* Cree un usuario de almacenamiento de objetos.
* Cree una clave S3 para el usuario.




== Grupos de almacenamiento de objetos

Use los métodos que se enumeran en la siguiente tabla para recuperar, crear o modificar grupos de almacenamiento de objetos.

|===
| Método HTTP | Ruta | Descripción 


| `GET` | `/v2.1/objectiam/groups` | Recuperar grupos de almacenamiento de objetos. 


| `GET` | `/v2.1/objectiam/groups/{id}` | Recupere un grupo de almacenamiento de objetos por ID. 


| `POST` | `/v2.1/objectiam/groups` | Cree un grupo de gestión de acceso a identidades de almacenamiento de objetos. 


| `PUT` | `/v2.1/objectiam/groups/{id}` | Modificar un grupo de almacenamiento de objetos identificado por ID. 


| `DELETE` | `/v2.1/objectiam/groups/{id}` | Eliminar un grupo de almacenamiento de objetos identificado por ID. 
|===


=== Atributos del grupo de almacenamiento de objetos

En la siguiente tabla se enumeran los atributos de almacenamiento del objeto.

|===
| Atributo | Tipo | Descripción 


| `id` | Cadena | El identificador único del grupo de almacenamiento de objetos. 


| `name` | Cadena | El nombre del grupo de almacenamiento de objetos. 


| `subtenant` | Cadena | Nombre del subarrendatario al que pertenece el grupo. 


| `subtenant_id` | Cadena | Identificador del subarrendatario al que pertenece el grupo. 


| `tenant` | Cadena | Nombre del inquilino al que pertenece el grupo. 


| `tenant_id` | Cadena | El identificador del inquilino al que pertenece el grupo. 


| `s3_policy` |   a| 
Política de S3 por ejemplo:

[listing]
----
"s3_policy": {
    "Statement": [
      {
        "Effect": "Allow",
        "Action": "s3:*",
        "Resource": "arn:aws:s3:::*"
      }
    ]
  }
----
|===


=== Recuperar grupos de almacenamiento de objetos

Use el método indicado en la siguiente tabla para recuperar todos los grupos de almacenamiento de objetos o un subconjunto de grupos de almacenamiento de objetos. Especificar un `subtenant_id` devolverá solo los grupos de almacenamiento de objetos que pertenecen a ese subinquilino.

|===
| Método HTTP | Ruta | Descripción | Parámetros 


| `GET` | `/v2.1/objectiam/groups` | Recupere todos los grupos de almacenamiento de objetos. De manera opcional, especifique un ID de subinquilino para recuperar solo los grupos de almacenamiento de objetos asociados con el subinquilino. | `subtenant_id (string)`: El identificador de subarrendatario asociado a los usuarios/grupos de Identity and Access Management (IAM).
`offset` y.. `limit`– consulte link:seapiref_netapp_service_engine_rest_apis.html#pagination>["Paginación común"] 
|===
Atributos de cuerpo de solicitud necesarios: `none`

*Ejemplo de cuerpo de solicitud:*

....
none
....
*Ejemplo de cuerpo de respuesta:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "total_records": 1,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 0,
    "limit": 20,
    "records": [
      {
        "id": "5eb1eff8bc5c0300011c989c",
        "name": "MyGroup",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant",
        "subtenant_id": "5e7c3af8aab46c00014ce878",
        "subtenant": "MySubtenant",
        "s3_policy": {
          "Statement": [
            {
              "Action": [
                "s3:*"
              ],
              "Effect": "Allow",
              "Resource": "arn:aws:s3:::*"
            }
          ]
        }
      }
    ]

....


=== Recupere un grupo de almacenamiento de objetos por ID

Utilice el método que se indica en la siguiente tabla para recuperar un grupo de almacenamiento de objetos por ID.

|===
| Método HTTP | Ruta | Descripción | Parámetros 


| `GET` | `/v2.1/objectiam/groups/{id}` | Recupere un grupo de almacenamiento de objetos por ID. | `id (string)`: El identificador único del grupo de almacenamiento de objetos. 
|===
Atributos de cuerpo de solicitud necesarios: `none`

*Ejemplo de cuerpo de solicitud:*

....
none
....
*Ejemplo de cuerpo de respuesta:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5eb1eff8bc5c0300011c989c",
        "name": "MyGroup",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant",
        "subtenant_id": "5e7c3af8aab46c00014ce878",
        "subtenant": "MySubtenant",
        "s3_policy": {
          "Statement": [
            {
              "Action": [
                "s3:*"
              ],
              "Effect": "Allow",
              "Resource": "arn:aws:s3:::*"
            }
          ]
        }
      }
    ]
  }
....


=== Cree un grupo de almacenamiento de objetos

Use el método indicado en lo siguiente para crear un grupo de almacenamiento de objetos.

|===
| Método HTTP | Ruta | Descripción | Parámetros 


| `POST` | `/v2.1/objectiam/groups/` | Cree un nuevo servicio de grupo de almacenamiento de objetos para los usuarios de almacenamiento de objetos host. | Ninguno 
|===
Atributos de cuerpo de solicitud necesarios: `name`, `subtenant_id`, `s3Policy`

*Ejemplo de cuerpo de solicitud:*

....
{
  "name": "MyNewGroup",
  "subtenant_id": "5e7c3af8aab46c00014ce878",
  "s3_policy": {
    "Statement": [
      {
        "Effect": "Allow",
        "Action": "s3:*",
        "Resource": "arn:aws:s3:::*"
      }
    ]
  }
}
....
*Ejemplo de cuerpo de respuesta:*

....
{
  "status": {
    "user_message": "Okay. Accepted for processing.",
    "verbose_message": "",
    "code": 202
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ed5fa312c356a0001a73841",
        "action": "create",
        "job_summary": "Create request is successfully submitted",
        "created": "2020-06-02T07:05:21.130260774Z",
        "updated": "2020-06-02T07:05:21.130260774Z",
        "object_id": "5ed5fa312c356a0001a73840",
        "object_type": "sg_groups",
        "object_name": "MyNewGroup",
        "status": "pending",
        "status_detail": "",
        "last_error": "",
        "user_id": "5ec626c0f038943eb46b0af1",
        "job_tasks": null
      }
    ]
  }
}
....


=== Modificar un grupo de almacenamiento de objetos

Utilice el método indicado en la siguiente tabla para modificar un grupo de almacenamiento de objetos.

|===
| Método HTTP | Ruta | Descripción | Parámetros 


| `PUT` | `/v2.1/objectiam/groups/{id}` | Modificar un grupo de almacenamiento de objetos. | `id (string)`: El identificador único del grupo de almacenamiento de objetos. 
|===
Atributos de cuerpo de solicitud necesarios: `name`, `subtenant_id`, `s3Policy`

*Ejemplo de cuerpo de solicitud:*

....
{
  "s3_policy": {
    "Statement": [
        {
        "Action": [
            "s3:ListAllMyBuckets",
            "s3:ListBucket",
            "s3:ListBucketVersions",
            "s3:GetObject",
            "s3:GetObjectTagging",
            "s3:GetObjectVersion",
            "s3:GetObjectVersionTagging"
        ],
        "Effect": "Allow",
        "Resource": "arn:aws:s3:::*"
        }
    ]
  }
}
....
*Ejemplo de cuerpo de respuesta:*

....
{
  "status": {
    "user_message": "Okay. Accepted for processing.",
    "verbose_message": "",
    "code": 202
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ed5fe822c356a0001a73859",
        "action": "update",
        "job_summary": "Update request is successfully submitted",
        "created": "2020-06-02T07:23:46.43550235Z",
        "updated": "2020-06-02T07:23:46.43550235Z",
        "object_id": "5ed5fa312c356a0001a73840",
        "object_type": "sg_groups",
        "object_name": "MyNewGroup",
        "status": "pending",
        "status_detail": "",
        "last_error": "",
        "user_id": "5ec626c0f038943eb46b0af1",
        "job_tasks": null
      }
    ]
  }
}
....


=== Eliminar un grupo de almacenamiento de objetos por ID

Use el método que se indica en la siguiente tabla para eliminar un grupo de almacenamiento de objetos por ID.

|===
| Método HTTP | Ruta | Descripción | Parámetros 


| `Delete` | `/v2.1/objectiam/groups/{id}` | Eliminar un grupo de almacenamiento de objetos por ID. | `id (string)`: El identificador único del grupo de almacenamiento de objetos. 
|===
Atributos de cuerpo de solicitud necesarios: `none`

*Ejemplo de cuerpo de solicitud:*

....
none
....
*Ejemplo de cuerpo de respuesta:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5eb1eff8bc5c0300011c989c",
        "name": "MyGroup",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant",
        "subtenant_id": "5e7c3af8aab46c00014ce878",
        "subtenant": "MySubtenant",
        "s3_policy": {
          "Statement": [
            {
              "Action": [
                "s3:*"
              ],
              "Effect": "Allow",
              "Resource": "arn:aws:s3:::*"
            }
          ]
        }
      }
    ]
  }
....


== Usuarios de almacenamiento de objetos

Utilice los métodos enumerados en la siguiente tabla para realizar las siguientes tareas:

* Recuperar, crear o modificar usuarios de almacenamiento de objetos.
* Cree claves S3, recupere claves S3 para un usuario o recupere claves por ID de clave.


|===
| Método HTTP | Ruta | Descripción 


| `GET` | `/v2.1/objectiam/users` | Recuperar usuarios de almacenamiento de objetos. 


| `GET` | `/v2.1/objectiam/users/{id}` | Recupere un usuario de almacenamiento de objetos por ID. 


| `POST` | `/v2.1/objectiam/users` | Cree un usuario de almacenamiento de objetos. 


| `PUT` | `/v2.1/objectiam/users/{id}` | Modificar un usuario de almacenamiento de objetos identificado por ID. 


| `DELETE` | `/v2.1/objectiam/users/{id}` | Eliminar un usuario de almacenamiento de objetos por ID. 


| `GET` | `/v2.1/objectiam/users/{user_id}/s3keys` | Obtener todas las claves S3 asignadas a un usuario. 


| `POST` | `/v2.1/objectiam/users/{user_id}/s3keys` | Cree claves S3. 


| `GET` | `/v2.1/objectiam/users/{user_id}/s3keys/{key_id}` | Obtenga claves S3 por ID de clave. 


| `DELETE` | `/v2.1/objectiam/users/{user_id}/s3keys/{key_id}` | Elimine claves S3 por ID de clave. 
|===


=== Atributos de usuario para almacenamiento de objetos

En la siguiente tabla se enumeran los atributos de usuario de almacenamiento de objetos.

|===
| Atributo | Tipo | Descripción 


| `id` | Cadena | El identificador único del usuario de almacenamiento de objetos. 


| `display_name` | Cadena | Nombre para mostrar del usuario. 


| `subtenant` | Cadena | El nombre del subarrendatario al que pertenece el usuario. 


| `subtenant_id` | Cadena | Identificador del subarrendatario al que pertenece el usuario. 


| `tenant` | Cadena | Nombre del inquilino al que pertenece el usuario. 


| `tenant_id` | Cadena | El identificador del inquilino al que pertenece el usuario. 


| `objectiam_user_urn` | Cadena | URN. 


| `sg_group_membership` | Cadena | Pertenencia al grupo StorageGRID de NetApp. Por ejemplo: "sg_Group_Membership": [ "5d2fb0fb4f47df00015274e3" ] 
|===


=== Recuperar usuarios de almacenamiento de objetos

Utilice el método que se indica en la siguiente tabla para recuperar todos los usuarios de almacenamiento de objetos o un subconjunto de usuarios de almacenamiento de objetos. Especificar un `subtenant_id` devolverá solo los grupos de almacenamiento de objetos que pertenecen a ese subinquilino.

|===
| Método HTTP | Ruta | Descripción | Parámetros 


| `GET` | `/v2.1/objectiam/users` | Recuperar todos los usuarios de almacenamiento de objetos. | `subtenant_id (string)`: El identificador de subarrendatario asociado a los usuarios/grupos de IAM.
`offset` y.. `limit` – consulte link:seapiref_netapp_service_engine_rest_apis.html#pagination>["Paginación común"] 
|===
Atributos de cuerpo de solicitud necesarios: `none`

*Ejemplo de cuerpo de solicitud:*

....
none
....
*Ejemplo de cuerpo de respuesta:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "total_records": 1,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 0,
    "limit": 20,
    "records": [
      {
        "id": "5eb2212d1cbe3b000134762e",
        "display_name": "MyUser",
        "subtenant": "MySubtenant",
        "subtenant_id": "5e7c3af8aab46c00014ce878",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant",
        "objectiam_user_urn": "urn:sgws:identity::96465636379595351967:user/myuser",
        "sg_group_membership": [
          "5eb1eff8bc5c0300011c989c"
        ]
      }
    ]
  }
}
....


=== Recupere un usuario de almacenamiento de objetos por ID

Utilice el método que se indica en la siguiente tabla para recuperar un almacenamiento de objetos utilice por ID.

|===
| Método HTTP | Ruta | Descripción | Parámetros 


| `GET` | `/v2.1/objectiam/users{id}` | Recupere un usuario de almacenamiento de objetos por ID. | `id`: El ID de cuenta de almacenamiento de objetos. 
|===
Atributos de cuerpo de solicitud necesarios: `none`

*Ejemplo de cuerpo de solicitud:*

....
none
....
*Ejemplo de cuerpo de respuesta:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5eb2212d1cbe3b000134762e",
        "display_name": "MyUser",
        "subtenant": "MySubtenant",
        "subtenant_id": "5e7c3af8aab46c00014ce878",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant",
        "objectiam_user_urn": "urn:sgws:identity::96465636379595351967:user/myuser",
        "sg_group_membership": [
          "5eb1eff8bc5c0300011c989c"
        ]
      }
    ]
  }
}
....


=== Cree un usuario de almacenamiento de objetos

Use el método indicado en la siguiente tabla para crear un usuario de almacenamiento de objetos.

|===
| Método HTTP | Ruta | Descripción | Parámetros 


| `POST` | `/v2.1/objectiam/users` | Cree un nuevo usuario de almacenamiento de objetos. | Ninguno 
|===
Atributos de cuerpo de solicitud necesarios: `display_name`, `subtenant_id`, `sg_group_membership`

*Ejemplo de cuerpo de solicitud:*

....
{
  "display_name": "MyUserName",
  "subtenant_id": "5e7c3af8aab46c00014ce878",
  "sg_group_membership": [
    "5ed5fa312c356a0001a73840"
  ]
}
....
*Ejemplo de cuerpo de respuesta:*

....
{
  "status": {
    "user_message": "Okay. Accepted for processing.",
    "verbose_message": "",
    "code": 202
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ed603712c356a0001a7386c",
        "action": "create",
        "job_summary": "Activate request is successfully submitted",
        "created": "2020-06-02T07:44:49.647815816Z",
        "updated": "2020-06-02T07:44:49.647815816Z",
        "object_id": "5ed603712c356a0001a7386d",
        "object_type": "sg_users",
        "object_name": "MyUserName",
        "status": "pending",
        "status_detail": "",
        "last_error": "",
        "user_id": "5ec626c0f038943eb46b0af1",
        "job_tasks": null
      }
    ]
  }
}
....


=== Modificar un usuario de almacenamiento de objetos

Utilice el método que se indica en la siguiente tabla para modificar un usuario de almacenamiento de objetos.

|===
| Método HTTP | Ruta | Descripción | Parámetros 


| `PUT` | `/v2.1/objectiam/users/{id}` | Modificar un usuario de almacenamiento de objetos identificado por ID. | `id`: El ID de usuario de almacenamiento de objetos. 
|===
Atributos de cuerpo de solicitud necesarios: `display_name`, `subtenant_id`, `sg_group_membership`

*Ejemplo de cuerpo de solicitud:*

....
{
  "display_name": "MyModifiedObjectStorageUser",
  "subtenant_id": "5e57a465896bd80001dd4961",
  "sg_group_membership": [
    "5e60754f9b64790001fe937b"
  ]
}
....
*Ejemplo de cuerpo de respuesta:*

....
{
  "status": {
    "user_message": "Okay. Accepted for processing.",
    "verbose_message": "",
    "code": 202
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ed604002c356a0001a73880",
        "action": "update",
        "job_summary": "Update request is successfully submitted",
        "created": "2020-06-02T07:47:12.205889873Z",
        "updated": "2020-06-02T07:47:12.205889873Z",
        "object_id": "5ed603712c356a0001a7386d",
        "object_type": "sg_users",
        "object_name": "MyUserName",
        "status": "pending",
        "status_detail": "",
        "last_error": "",
        "user_id": "5ec626c0f038943eb46b0af1",
        "job_tasks": null
      }
    ]
  }
}
....


=== Asignar todas las claves S3 a un usuario de almacenamiento de objetos

Use el método que se indica en la siguiente tabla para asignar todas las claves de S3 a un usuario de almacenamiento de objetos.

|===
| Método HTTP | Ruta | Descripción | Parámetros 


| `GET` | `/v2.1/objectiam/users/{user_id}/s3keys` | Cree una clave S3 para un usuario de almacenamiento de objetos. | `user_id (string)`: El identificador de usuario de almacenamiento de objetos. 
|===
Atributos de cuerpo de solicitud necesarios: `none`

*Ejemplo de cuerpo de solicitud:*

....
none
....
*Ejemplo de cuerpo de respuesta:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5e66de2509a74c0001b895e7",
        "display_name": "****************HNDE",
        "subtenant_id": "5e57a465896bd80001dd4961",
        "subtenant": "BProject",
        "objectiam_user_id": "5e66c77809a74c0001b89598",
        "objectiam_user": "MyNewObjectStorageUser",
        "objectiam_user_urn": "urn:sgws:identity::09936502886898621050:user/mynewobjectstorageuser",
        "expires": "2020-04-07T10:40:52Z"
      }
    ]
....


=== Cree una clave S3 para un usuario de almacenamiento de objetos

Utilice el método que se indica en los siguientes casos para crear una clave S3 para un usuario de almacenamiento de objetos.

|===
| Método HTTP | Ruta | Descripción | Parámetros 


| `POST` | `/v2.1/objectiam/users/{user_id}/s3keys` | Cree una clave S3 para un usuario de almacenamiento de objetos. | `user_id (string)`: El identificador de usuario de almacenamiento de objetos. 
|===
Atributos de cuerpo de solicitud necesarios: `expires` (cadena)


NOTE: La fecha/hora de caducidad de la clave se establece en UTC; debe establecerse en el futuro.

*Ejemplo de cuerpo de solicitud:*

....
{
  "expires": "2020-04-07T10:40:52Z"
}
....
*Ejemplo de cuerpo de respuesta:*

....
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "id": "5e66de2509a74c0001b895e7",
        "display_name": "****************HNDE",
        "subtenant_id": "5e57a465896bd80001dd4961",
        "subtenant": "BProject",
        "objectiam_user_id": "5e66c77809a74c0001b89598",
        "objectiam_user": "MyNewObjectStorageUser",
        "objectiam_user_urn": "urn:sgws:identity::09936502886898621050:user/mynewobjectstorageuser",
        "expires": "2020-04-07T10:40:52Z",
        "access_key": "PL86KPEBN6XT4T7UHNDE",
        "secret_key": "FlD/YWAM7JMr9gG8pumU8dzvcTLMzLYtUe2lNzcA"
      }
    ]
  }
}
....


=== Obtenga las claves S3 para un usuario de almacenamiento de objetos por ID de clave

Use el método que se indica en la siguiente tabla para obtener claves S3 para un usuario de almacenamiento de objetos por ID de clave.

|===
| Método HTTP | Ruta | Descripción | Parámetros 


| `GET` | `/v2.1/objectiam/users/{user_id}/s3keys/{key_id}` | Obtenga claves S3 por ID de clave.  a| 
* `user_id (string)`: El ID de usuario de almacenamiento de objetos. Por ejemplo: 5e66c77809a74c0001b89598
* `key_id (string)`: Clave S3 por ejemplo: 5e66de2509a74c0001b895e7


|===
Atributos de cuerpo de solicitud necesarios: `none`

*Ejemplo de cuerpo de solicitud:*

....
none
....
*Ejemplo de cuerpo de respuesta:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ecc7bb9b5d2730001f798fb",
        "display_name": "****************XCXD",
        "subtenant_id": "5e7c3af8aab46c00014ce878",
        "subtenant": "MySubtenant",
        "objectiam_user_id": "5eb2212d1cbe3b000134762e",
        "objectiam_user": "MyUser",
        "objectiam_user_urn": "urn:sgws:identity::96465636379595351967:user/myuser",
        "expires": "2020-05-27T00:00:00Z"
      }
    ]
  }
}
....


=== Elimine una clave de S3 según el ID de clave

Use el método que se indica en la siguiente tabla para eliminar una clave de S3 por ID de clave.

|===
| Método HTTP | Ruta | Descripción | Parámetros 


| `Delete` | `/v2.1/objectiam/users/{user_id}/s3keys/{key_id}` | Elimine clave S3 según ID de clave.  a| 
* `user_id (string)`: El ID de usuario de almacenamiento de objetos. Por ejemplo: 5e66c77809a74c0001b89598
* `key_id (string)`: Clave S3 por ejemplo: 5e66de2509a74c0001b895e7


|===
Atributos de cuerpo de solicitud necesarios: `none`

*Ejemplo de cuerpo de solicitud:*

....
none
....
*Ejemplo de cuerpo de respuesta:*

....
No content to return for succesful execution
....


== Cuentas de almacenamiento de objetos

Utilice los métodos enumerados en la siguiente tabla para realizar las siguientes tareas:

* Recuperar, activar o modificar cuentas de almacenamiento de objetos.
* Cree bloques S3.


|===
| Método HTTP | Ruta | Descripción 


| `GET` | `/v2.1/objectstorage/accounts` | Recuperar cuentas de almacenamiento de objetos. 


| `GET` | `/v2.1/objectstorage/accounts/{id}` | Recupere una cuenta de almacenamiento de objetos por ID. 


| `POST` | `/v2.1/objectstorage/accounts` | Cree una cuenta de almacenamiento de objetos. 


| `PUT` | `/v2.1/objectstorage/accounts/{id}` | Modificar una cuenta de almacenamiento de objetos identificada por ID. 


| `DELETE` | `/v2.1/objectstorage/accounts/{id}` | Modificar una cuenta de almacenamiento de objetos identificada por ID. 


| `GET` | `/v2.1/objectstorage/buckets` | Obtenga cubos de S3. 


| `POST` | `/v2.1/objectstorage/buckets` | Cree bloques S3. 
|===


=== Atributos de cuenta de almacenamiento de objetos

En la siguiente tabla se enumeran los atributos de cuenta de almacenamiento de objetos.

|===
| Atributo | Tipo | Descripción 


| `id` | Cadena | El identificador único del usuario de almacenamiento de objetos. 


| `subtenant_id` | Cadena | Identificador de la instancia de un objeto subarrendatario. 


| `quota_gb` | Entero | El tamaño del recurso compartido o del disco. 
|===


=== Recupere todas las cuentas de almacenamiento de objetos

Use el método indicado en la siguiente tabla para recuperar todas las cuentas de almacenamiento de objetos o un subconjunto de cuentas de almacenamiento de objetos.

|===
| Método HTTP | Ruta | Descripción | Parámetros 


| `GET` | `/v2.1/objectstorage/accounts` | Recuperar todos los usuarios de almacenamiento de objetos. | `offset` y.. `limit`– . consulte link:seapiref_netapp_service_engine_rest_apis.html#pagination>["Paginación común"] 
|===
Atributos de cuerpo de solicitud necesarios: `none`

*Ejemplo de cuerpo de solicitud:*

....
none
....
*Ejemplo de cuerpo de respuesta*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "total_records": 19,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 3,
    "limit": 1,
    "records": [
      {
        "id": "5ec6119e6344d000014cdc41",
        "name": "MyTenant - MySubtenant",
        "subtenant": " MySubtenant",
        "subtenant_id": "5ea8c5e083a9f80001b9d705",
        "tenant": "E- MyTenant",
        "tenant_id": "5d914499869caefed0f39eee",
        "sg_account_id": "29420999312809208626",
        "quota_gb": 100,
        "sg_instance_name": "NSE StorageGRID Dev1",
        "sg_instance_id": "5e3ba2840271823644cb8ab6"
      }
    ]
  }
}
....


=== Recupere una cuenta de almacenamiento de objetos por ID

Utilice el método que se indica en la siguiente tabla para recuperar una cuenta de almacenamiento de objetos por ID.

|===
| Método HTTP | Ruta | Descripción | Parámetros 


| `GET` | `/v2.1/objectstorage/accounts/{id}` | Recupere una cuenta de almacenamiento de objetos por ID. | `id`: El ID de cuenta de almacenamiento de objetos. 
|===
Atributos de cuerpo de solicitud necesarios: `none`

*Ejemplo de cuerpo de solicitud:*

....
none
....
*Ejemplo de cuerpo de respuesta:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ec6119e6344d000014cdc41",
        "name": "MyTenant - MySubtennant",
        "subtenant": " MySubtennant",
        "subtenant_id": "5ea8c5e083a9f80001b9d705",
        "tenant": " MyTenant",
        "tenant_id": "5d914499869caefed0f39eee",
        "sg_account_id": "29420999312809208626",
        "quota_gb": 100,
        "sg_instance_name": "NSE StorageGRID Dev1",
        "sg_instance_id": "5e3ba2840271823644cb8ab6"
      }
    ]
  }
....


=== Activar una cuenta de almacenamiento de objetos

Utilice el método indicado en la siguiente tabla para activar una cuenta de almacenamiento de objetos.

|===
| Método HTTP | Ruta | Descripción | Parámetros 


| `POST` | `/v2.1/objectstorage/accounts` | Activar un servicio de almacenamiento de objetos. | Ninguno 
|===
Atributos de cuerpo de solicitud necesarios: `subtenant_id, quota_gb`

*Ejemplo de cuerpo de solicitud:*

....
{
  "subtenant_id": "5ecefbbef418b40001f20bd6",
  "quota_gb": 20
}
....
*Ejemplo de cuerpo de respuesta:*

....
{
  "status": {
    "user_message": "Okay. Accepted for processing.",
    "verbose_message": "",
    "code": 202
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ed608542c356a0001a73893",
        "action": "create",
        "job_summary": "Activate request for Sub Tenant MyNewSubtenant is successfully submitted",
        "created": "2020-06-02T08:05:40.017362022Z",
        "updated": "2020-06-02T08:05:40.017362022Z",
        "object_id": "5ed608542c356a0001a73894",
        "object_type": "sg_accounts",
        "object_name": "MyTenant - MyNewSubtenant",
        "status": "pending",
        "status_detail": "",
        "last_error": "",
        "user_id": "5ec626c0f038943eb46b0af1",
        "job_tasks": null
      }
    ]
  }
}
....


=== Modificar una cuenta de almacenamiento de objetos

Utilice el método indicado en la siguiente tabla para modificar una cuenta de almacenamiento de objetos.

|===
| Método HTTP | Ruta | Descripción | Parámetros 


| `PUT` | `/v2.1/objectstorage/accounts/{id}` | Modificar un servicio de almacenamiento de objetos (como, cambiar la cuota). | `id (string)`: El ID de cuenta de almacenamiento de objetos. 
|===
Atributos de cuerpo de solicitud necesarios: `name`, `subtenant_id`, `quota_gb`

*Ejemplo de cuerpo de solicitud:*

....
{
  "name": "MyTenant - MyNewSubtenant",
  "subtenant_id": "5ecefbbef418b40001f20bd6",
  "quota_gb": 30
}
....
*Ejemplo de cuerpo de respuesta:*

....
{
  "status": {
    "user_message": "Okay. Accepted for processing.",
    "verbose_message": "",
    "code": 202
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ed609162c356a0001a73899",
        "action": "update",
        "job_summary": "Update request is successfully submitted",
        "created": "2020-06-02T08:08:54.841652098Z",
        "updated": "2020-06-02T08:08:54.841652098Z",
        "object_id": "5ed608542c356a0001a73894",
        "object_type": "sg_accounts",
        "object_name": "MyTenant - MyNewSubtenant",
        "status": "pending",
        "status_detail": "",
        "last_error": "",
        "user_id": "5ec626c0f038943eb46b0af1",
        "job_tasks": null
      }
    ]
  }
}
....


=== Eliminar una cuenta de almacenamiento de objetos

Antes de poder eliminar una cuenta de almacenamiento de objetos, primero debe eliminar todos los grupos, usuarios y bloques asociados. Utilice el método que figura en la siguiente tabla para eliminar una cuenta de almacenamiento de objetos.


NOTE: Use la utilidad compatible con S3 para eliminar bloques. No se pueden eliminar bloques del motor de servicio de NetApp.

|===
| Método HTTP | Ruta | Descripción | Parámetros 


| `Delete` | `/v2.1/objectstorage/accounts/{id}` | Eliminar una cuenta de almacenamiento de objetos. | `id (string)`: El ID de cuenta de almacenamiento de objetos. 
|===
Atributos de cuerpo de solicitud necesarios: `none`

*Ejemplo de cuerpo de solicitud:*

....
{
  "name": "MyTenant - MyNewSubtenant",
  "subtenant_id": "5ecefbbef418b40001f20bd6",
  "quota_gb": 30
}
....
*Ejemplo de cuerpo de respuesta:*

....
{
  "status": {
    "user_message": "string",
    "verbose_message": "string",
    "code": "string"
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5d2fb0fb4f47df00015274e3",
        "action": "string",
        "object_id": "5d2fb0fb4f47df00015274e3",
        "object_type": "string",
        "status": "string",
        "status_detail": "string",
        "last_error": "string",
        "user_id": "5d2fb0fb4f47df00015274e3",
        "link": "string"
      }
    ]
  }
}
....


== Cubos de almacenamiento de objetos

Use las API de la siguiente tabla para crear y recuperar bloques de almacenamiento de objetos.

|===
| Método HTTP | Ruta | Descripción 


| `GET` | `/v2.1/objectstorage/buckets` | Recuperar cubos de almacenamiento de objetos. 


| `POST` | `/v2.1/objectstorage/buckets` | Crear un bloque de almacenamiento de objetos. 
|===


=== Atributos de bucket de almacenamiento de objetos

En la siguiente tabla se enumeran los atributos de bloque de almacenamiento de objetos.

|===
| Atributo | Tipo | Descripción 


| `id` | Cadena | El identificador único del usuario de almacenamiento de objetos. 


| `Name` | Cadena | El nombre del bloque. 


| `subtenant_id` | Cadena | El identificador del subinquilino al que pertenece el bloque. 
|===


=== Recuperar bloques de S3

Utilice el método indicado en la siguiente tabla para recuperar bloques de S3.

|===
| Método HTTP | Ruta | Descripción | Parámetros 


| `GET` | `/v2.1/objectstorage/buckets` | Recuperar bloques de S3. | `Subtenant_id`: El subinquilino que posee el cubo. 
|===
Atributos de cuerpo de solicitud necesarios: `none`

*Ejemplo de cuerpo de solicitud:*

....
none
....
*Ejemplo de cuerpo de respuesta:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "creationTime": "2020-06-02T08:13:25.695Z",
        "name": "mybucket"
      }
    ]
  }
}
....


=== Cree bloques S3

Utilice el método que se indica en la siguiente tabla para crear un bloque de S3.


NOTE: Antes de poder crear un bloque, debe existir una cuenta de almacenamiento de objetos para el subinquilino.

|===
| Método HTTP | Ruta | Descripción | Parámetros 


| `POST` | `/v2.1/objectstorage/buckets` | Cree un bloque de S3. | Ninguno 
|===
Atributos de cuerpo de solicitud necesarios:

* `name` (Cadena): Nombre de bloque de S3 (solo caracteres numéricos o minúsculas)
* `subtenant_id` (Cadena): ID del subinquilino al que pertenece el bloque de S3


*Ejemplo de cuerpo de solicitud:*

....
{
  "name": "mybucket",
  "subtenant_id": "5ecefbbef418b40001f20bd6"
}
....
*Ejemplo de cuerpo de respuesta:*

....
{
  "status": {
    "user_message": "Okay. Accepted for processing.",
    "verbose_message": "",
    "code": 202
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ed60a232c356a0001a7389e",
        "action": "create",
        "job_summary": "Create request is successfully submitted",
        "created": "2020-06-02T08:13:23.105015108Z",
        "updated": "2020-06-02T08:13:23.105015108Z",
        "object_id": "5ed60a232c356a0001a7389f",
        "object_type": "sg_buckets",
        "object_name": "mybucket",
        "status": "pending",
        "status_detail": "",
        "last_error": "",
        "user_id": "5ec626c0f038943eb46b0af1",
        "job_tasks": null
      }
    ]
  }
}
....