---
sidebar: sidebar 
permalink: seapiref_jobs.html 
keywords: netapp, keystone, jobs, 
summary: Trabajos de Keystone API 
---
= Trabajos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Use las API de trabajos para revisar detalles del trabajo. Para obtener más información sobre cómo trabajar con trabajos, vea API de objetos de trabajo y procesos asíncronos.



== Recuperar trabajos

Utilice el método que se muestra en la siguiente tabla para recuperar todos los trabajos o un subconjunto de los trabajos. Especificar un `tenant_id` sólo devolverá los trabajos que pertenecen a ese arrendatario.

|===
| Método HTTP | Ruta | Descripción | Parámetros 


| `GET` | `/v2.1/jobs` | Recuperar trabajos. | `tenant_id`: (Opcional) devuelve los almacenes de bloque que pertenecen al arrendatario especificado.
`offset` y.. `limit`– consulte link:seapiref_netapp_service_engine_rest_apis.html#pagination>["Paginación común"] 
|===
Atributos de cuerpo de solicitud necesarios: `none`

*Ejemplo de cuerpo de solicitud:*

....
none
....
*Ejemplo de cuerpo de respuesta:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "total_records": 2625,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 0,
    "limit": 1,
    "records": [
      {
        "id": "5ed72c8c6342e90001439d54",
        "action": "create",
        "job_summary": "Create request is successfully submitted",
        "created": "2020-06-03T04:52:28.478Z",
        "updated": "2020-06-03T04:52:32.636Z",
        "object_id": "5ed72c8c6342e90001439d55",
        "object_type": "sg_buckets",
        "object_name": "test1234",
        "status": "successful",
        "status_detail": "Creation of s3 bucket 'test1234' completed successfully.",
        "last_error": "",
        "user_id": "5e85225af038943eb4b74684",
        "job_tasks": [
          {
            "id": "5ed72c8c6342e90001439d57",
            "job_id": "5ed72c8c6342e90001439d54",
            "action": "create",
            "driver": "storagegrid_ansible",
            "object_id": "5ed72c8c6342e90001439d55",
            "object_type": "sg_buckets",
            "resource_type": "sg_bucket",
            "status": "successful",
            "status_detail": "Worker completed task successfully.",
            "last_error": "",
            "user_id": "5e85225af038943eb4b74684",
            "request_payload": {
              "grid_account_id": "05336917559886003354",
              "grid_admin_base_url": "https://sggmi-dev.dev.ausngs.netapp.au/api/v3",
              "org_password": "netapp01",
              "org_username": "root",
              "s3_bucket_name": "test1234"
            }
          }
        ]
      }
    ]
  }
}
....


=== Recuperar un trabajo por ID de trabajo

Utilice el método que se muestra en la siguiente tabla para recuperar un trabajo por ID.

|===
| Método HTTP | Ruta | Descripción | Parámetros 


| `GET` | `/v2.1/jobs/{id}` | Recuperar un trabajo por ID. | `id (string)`: El identificador único del trabajo. 
|===
Atributos de cuerpo de solicitud necesarios: `job identifier`

*Ejemplo de cuerpo de solicitud:*

....
none
....
*Ejemplo de cuerpo de respuesta:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "id": "5e66f18e09a74c0001b89640",
        "action": "create",
        "job_summary": "Create S3 bucket for Sub Tenant",
        "created": "2020-03-10T01:46:54.097Z",
        "updated": "2020-03-10T01:46:57.664Z",
        "object_id": "5e66f18e09a74c0001b89641",
        "object_type": "sg_buckets",
        "status": "successful",
        "status_detail": "Creation of s3 bucket 'mys3bucket' completed successfully.",
        "last_error": "",
        "user_id": "5bbee380a2df7a04d43acaee",
        "job_tasks": [
          {
            "id": "5e66f18e09a74c0001b89642",
            "job_id": "5e66f18e09a74c0001b89640",
            "action": "create",
            "driver": "storagegrid_ansible",
            "object_id": "5e66f18e09a74c0001b89641",
            "object_type": "sg_buckets",
            "resource_type": "sg_bucket",
            "status": "successful",
            "status_detail": "Worker completed task successfully.",
            "last_error": "",
            "user_id": "5bbee380a2df7a04d43acaee",
            "request_payload": {
              "grid_account_id": "47490102387197219062",
              "grid_admin_base_url": "https://sggmi-dev.dev.ausngs.netapp.au/api/v3",
              "org_password": "netapp01",
              "org_username": "root",
              "s3_bucket_name": "mys3bucket"
            }
          }
        ]
      }
    ]
  }
}
....


== API y procesos asíncronos de objetos de trabajo

Algunas de las llamadas API, especialmente las que se utilizan para agregar o modificar recursos, pueden tardar más tiempo en completarse que otras llamadas. El motor de servicio de NetApp procesa de forma asíncrona estas solicitudes de larga ejecución.

Después de realizar una llamada API que se ejecuta de forma asíncrona, el código de respuesta HTTP 202 indica que la solicitud se ha validado y aceptado correctamente, pero que aún no se ha completado. La solicitud se procesa como una tarea en segundo plano que continúa ejecutándose después de la respuesta HTTP inicial al cliente. La respuesta incluye el objeto de trabajo anclando la solicitud, incluido su identificador único.



=== Consultar el objeto de trabajo asociado con una solicitud de API

El objeto de trabajo devuelto en la respuesta HTTP contiene varias propiedades. Puede consultar la propiedad state para determinar si la solicitud se completó correctamente. Un objeto de trabajo puede estar en uno de los siguientes estados:

* NORMAL
* ADVERTENCIA
* FALLOS_PARCIALES
* ERROR


Existen dos técnicas que se pueden utilizar al sondear un objeto de trabajo para detectar un estado de terminal para la tarea, ya sea con éxito o con errores:

* Solicitud de sondeo estándar: El estado del trabajo actual se devuelve inmediatamente.
* Solicitud de sondeo largo: Cuando el estado del trabajo pasa A NORMAL, ERROR o PARCIAL_FRES.




=== Pasos para una solicitud asíncrona

Puede utilizar el siguiente procedimiento de alto nivel para completar una llamada API asíncrona:

. Emita la llamada de API asíncrona.
. Reciba una respuesta HTTP 202 que indique la aceptación correcta de la solicitud.
. Extraiga el identificador del objeto de trabajo del cuerpo de respuesta.
. Dentro de un bucle, espere a que el objeto de trabajo alcance el estado de terminal NORMAL, ERROR o PARTIAL_FALLAS.
. Verifique el estado del terminal del trabajo y recupere el resultado del trabajo.

