---
sidebar: sidebar 
permalink: sewebiug_add_a_subscribed_service.html 
keywords: netapp, keystone, add, cloud, service, 
summary: Keystone añade un servicio cloud 
---
= Agregar un servicio cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
En esta sección se describe cómo añadir un servicio cloud.

El motor de servicio de NetApp admite Azure NetApp Files.

.Antes de empezar
Necesita información sobre los servicios cloud, incluidas credenciales para conectarse al servicio. La información varía con el tipo de servicio de cloud.

.Pasos
. Seleccione *Servicios en la nube* en el menú.
. Haga clic en *Crear*.
. En la página Create Cloud Service, seleccione el tipo de servicio cloud y, a continuación, complete la información relevante para ese tipo de servicio:
+
*Azure:*

+
.. Seleccione el subarrendatario.
.. Introduzca un nombre para el entorno de trabajo de OCCM que se creará para el servicio.
.. Introduzca el ID de directorio (inquilino) de Azure, el ID de cliente de Azure, el secreto de cliente de Azure y el nombre del servicio de cloud.


. Especifique las etiquetas del servicio, si es necesario.
. Haga clic en *Crear*.

