---
sidebar: sidebar 
permalink: sewebiug_getting_started_overview.html 
keywords: netapp, keystone, getting, started, overview, 
summary: Descripción general del inicio de Keystone 
---
= Descripción general
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
En esta sección se describe cómo comenzar a utilizar el portal del motor de servicio de NetApp.


NOTE: Al desplazarse por el portal del motor de servicios de NetApp, puede comprobar que cierta información, como la región y la zona, se rellena automáticamente en función de la configuración de la suscripción configurada por el equipo de soporte.

Para comenzar sus actividades en este portal:

* Inicie sesión en la interfaz web del motor de servicios de NetApp.
+
** Inicie sesión con un nombre de usuario y una contraseña
** Inicie sesión con SSO de NetApp para obtener más información, consulte link:sewebiug_log_in_to_the_netapp_service_engine_web_interface.html["Inicie sesión en la interfaz web del motor de servicios de NetApp"]


* Seleccione inquilino. Aparecerá el panel de control. Para obtener más información, consulte link:sewebiug_dashboard.html["Consulta la consola de Keystone"]


Para obtener información general de la interfaz web del motor de servicios de NetApp, consulte link:sewebiug_netapp_service_engine_web_interface_overview.html["Información general de la interfaz web del motor de servicios de NetApp"]
