---
sidebar: sidebar 
permalink: sewebiug_working_with_object_storage_overview.html 
keywords: netapp, keystone, working, object, storage, overview, 
summary: Keystone está trabajando con información general sobre almacenamiento de objetos 
---
= Descripción general
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
El almacenamiento de objetos requiere una suscripción al servicio de almacenamiento de objetos. Cuando hay un servicio de almacenamiento de objetos disponible como parte de la suscripción, el almacenamiento se debe inicializar para poder utilizarlo.

Con el almacenamiento de objetos, los objetos se almacenan en bloques S3. El acceso a los bloques de S3 se gestiona a través de permisos establecidos en grupos de almacenamiento de objetos. A los usuarios de almacenamiento de objetos se les concede la pertenencia a uno o más grupos de almacenamiento de objetos, que heredan los permisos de la pertenencia al grupo.

Cada usuario de almacenamiento de objetos tiene claves S3 asociadas que permiten el acceso al almacenamiento de objetos.


NOTE: El acceso al almacenamiento de objetos se realiza mediante un explorador compatible con S3.

En esta sección se describe cómo gestionar el almacenamiento de objetos, y se incluye cómo:

* Inicializar el almacenamiento de objetos.
* Cree bloques S3.
+
No es posible eliminar bloques de S3 a través del portal web del motor de servicios de NetApp; elimine estos bloques con un explorador compatible con S3.

* Crear y gestionar grupos de almacenamiento de objetos.
* Cree y gestione usuarios de almacenamiento de objetos, incluida la creación de claves S3.

