---
sidebar: sidebar 
permalink: sewebiug_managing_subscribed_services_overview.html 
keywords: netapp, keystone, managing, cloud, services, overview, 
summary: Información general sobre la gestión de servicios cloud de Keystone 
---
= Descripción general
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cuando se registró con el motor de servicios de NetApp, puede gestionar sus servicios de Cloud Volumes (CVS) a través del portal web Service Engine de NetApp. Estos recursos incluyen:

* Azure NetApp Files (ANF)
* (Futuro) Amazon Web Services (AWS)
* (Futuro) Google Cloud Platform (GCP)
+
Solo puede registrar las suscripciones de CVS existentes con Service Engine de NetApp; para crear una nueva suscripción, cree la suscripción CVS de la forma normal y, después, registrarla con el Service Engine de NetApp con sus credenciales de suscripción.

+
En esta sección se describe cómo gestionar los servicios de cloud




NOTE: La gestión de servicios cloud requiere acceso de administrador de clientes.

Podrá:

* Consulte una lista de servicios cloud
* Agregar un servicio cloud
* Modifique los detalles del servicio cloud
* Eliminar un servicio cloud

