---
sidebar: sidebar 
permalink: sewebiug_modify_an_object_storage_user.html 
keywords: netapp, keystone, modify, object, storage, user, 
summary: Keystone modifique un usuario de almacenamiento de objetos 
---
= Modificar un usuario de almacenamiento de objetos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Use este método para modificar los detalles de un usuario de almacenamiento de objetos, como el nombre de usuario y el grupo al que están asignados.

.Pasos
. Vea el usuario de almacenamiento de objetos link:sewebiug_view_the_object_storage_group_and_users.html["Ver los usuarios y el grupo de almacenamiento de objetos"].
. Asegúrese de que el subarrendatario correcto está seleccionado y ha hecho clic en la ficha *usuarios*.
. Localice el usuario en la lista y haga clic en el icono de edición para ese usuario.
+
Para obtener información detallada sobre cómo trabajar con elementos de las listas, consulte link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view-actions["Acciones de vista de lista"].

. En el cuadro de diálogo *Editar usuario*, cambie el grupo de almacenamiento de objetos del usuario.
. Haga clic en *Actualizar*. Esto crea un trabajo para actualizar el grupo para el usuario. Para obtener información acerca del seguimiento de trabajos, consulte link:sewebiug_netapp_service_engine_web_interface_overview.html#jobs-and-job-status-indicator["aquí"].

