---
sidebar: sidebar 
permalink: sewebiug_define_network_configurations.html 
keywords: netapp, keystone, subnet, subtenant, network, tenant network, IPspace, VLAN, port 
summary: Cree y elimine subredes 
---
= Definir las configuraciones de red para inquilinos y subinquilinos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Un proveedor de servicios o un administrador de partners pueden definir configuraciones de red para inquilinos en función de sus zonas de suscripción y asignar VLAN a cada configuración de red. También pueden crear una subred con cada VLAN que pertenezca a la misma zona y al mismo tenancy, y asignarla a un subinquilino bajo ese usuario.

Se requiere una red de arrendatarios preconfigurada para crear la subred. Se requiere una subred cuando un subinquilino o un cliente final aprovisiona servidores de archivos o almacenes de bloques. Las máquinas virtuales de almacenamiento de archivos y bloques pertenecen a los subclientes del motor de servicios de NetApp, mientras que las pertenecen a espacios IP de ONTAP. Cuando define el límite de redes en un nivel de subinquilino, el subinquilino del motor de servicio de NetApp se asigna a un espacio IP de ONTAP único para esa zona. De este modo, se elimina el riesgo y se garantiza que dos subinquilinos distintos no seleccionen el mismo ID de VLAN y que terminen en el mismo espacio IP.

* Puede haber varias subredes creadas en cada zona. Para cada zona en una arquitectura por tenancy, hay una lista asignada de VLAN. Para todas estas VLAN disponibles, se pueden crear las subredes correspondientes. Hay una asignación de 1:1 entre una subred y una VLAN. Mientras que, hay una asignación a muchas entre las subredes y la zona.
* Un inquilino puede tener varias subredes, una para cada VLAN disponible en una zona. Se muestran bajo una sola configuración de red para cada zona.
* Solo puede haber una VLAN para cada subred de red. Cada configuración de red muestra una lista de las VLAN disponibles.
* Sólo se puede crear una subred para una combinación de zona y VLAN para un subinquilino.



NOTE: Un administrador de inquilinos solo puede ver las configuraciones de red para su cliente y las subredes para sus subusuarios.



== Defina una configuración de red para un inquilino

Como administrador de partners, puede crear configuraciones de red para cada inquilino. Se puede asignar un pool VLAN único y configurable a cada cliente en función de su requisito. Cuando se elimina un inquilino, las VLAN asociadas se devuelven al pool de VLAN de inquilino.

.Antes de empezar
* Asegúrese de que se hayan creado los inquilinos
* Debe conocer la configuración de zona, VLAN, CIDR de subred y anulación de puerto


.Pasos
. En *ADMINISTRACIÓN* > *arrendatarios*, seleccione el arrendatario requerido.
. Haga clic en el icono de red. Se muestra la pantalla redes con la lista de configuraciones de red para el arrendatario.
. Haga clic en *Crear red*. Especifique la zona, la VLAN y la sustitución de puerto, si corresponde. Si la sustitución del puerto está definida, seleccione el puerto asignado en el menú desplegable. Para todas las conexiones de red para ese inquilino, se utiliza este puerto y no el puerto predeterminado.
+

NOTE: El equipo de soporte configura la anulación del puerto durante la configuración de las zonas. Si no se especifica una sustitución de puerto, la red utiliza el puerto predeterminado y crea una nueva VLAN para ese inquilino.

. Haga clic en *Crear*. La nueva configuración de red se muestra para el arrendatario en la pantalla redes.


Si se crea la configuración de red de una zona, solo se pueden asignar nuevas VLAN a la configuración de red. Haga clic en el icono *+* y agregue los detalles de sustitución de VLAN y puerto. Haga clic en *Actualizar*.



== Cree una subred para un subarrendatario

Como administrador asociado, puede crear subredes para sus subarrendatarios desde *REDES* > *subredes*. La definición de subred incluye el identificador de VLAN que se implementa en ONTAP, el rango de direcciones CIDR y una especificación de ruta. Una subred está alineada con una VLAN dentro de un inquilino y una zona. No puede crear dos subredes con la misma VLAN para una zona.

.Antes de empezar
* La configuración de VLAN y zona ya debería haberse completado para el inquilino
* Debe tener en cuenta los requisitos de la subred que se creará


.Pasos
. Seleccione el arrendatario requerido. Los subarrendatarios para los que cree las subredes deben estar bajo este arrendatario.
. Haga clic en *REDES* > *subredes*. Puede ver la lista de subredes creadas para sus subarrendatarios en la página *subredes*.
. Haga clic en *Crear subred*.
. Especifique el subinquilino, la zona, el nombre de la subred, VLAN y la subred CIDR. También puede agregar etiquetas y especificaciones de ruta.
+

NOTE: En la especificación de ruta, el *destino* debe ser único y parte de la VLAN mencionada, y varias rutas pueden tener el mismo valor para *Métrico*.

. Haga clic en *Crear*.



NOTE: Una subred no se puede editar ni eliminar. Solo puede editar las etiquetas asociadas.
