---
sidebar: sidebar 
permalink: sewebiug_create_a_disk_from_a_snapshot.html 
keywords: netapp, keystone, create, disk, snapshot 
summary: Crear un disco a partir de una instantánea 
---
= Crear un disco a partir de una instantánea
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Es posible crear un disco nuevo a partir de una instantánea existente. El nuevo disco, clonado a partir de la instantánea, tiene las mismas propiedades que el disco desde el que se crea la instantánea.

.Pasos
. Seleccione *ALMACENAMIENTO EN BLOQUE* en el panel de navegación izquierdo y seleccione *discos*. Se muestra la lista de discos existentes para el cliente.
. Haga clic en *Crear disco* y seleccione *Clonar desde instantánea*. Como alternativa, si conoce el disco cuya instantánea desea utilizar para la clonación, puede localizar el disco y hacer clic en el botón de copia situado junto a él. El disco debe estar en estado operativo. Aparece la pantalla *Crear disco desde Snapshot* con todos los discos para el arrendatario. Puede filtrar discos por región, zona y subarrendatario. Es posible seleccionar cualquier disco que esté en estado operativo. Para obtener más información acerca de los estados de objeto, consulte link:sewebiug_netapp_service_engine_web_interface_overview.html#object-states["estados de objeto"]
. Seleccione la casilla de verificación situada junto al disco que desee y haga clic en *Siguiente*. Se muestran las snapshots del disco.
+

NOTE: Para el disco seleccionado, si existen algunas copias de Snapshot creadas en el entorno de SnapCenter fuera del motor de servicio de NetApp, es posible encontrar estas copias de Snapshot importadas y enumeradas para su selección. Es posible seleccionar estas snapshots importadas y clonar los discos nuevos a partir de ellas.

+
Puede buscar una copia de Snapshot en particular o seleccionar el tipo de programación para filtrar las copias de Snapshot.

. Seleccione la casilla de verificación situada junto a la instantánea desde la que desea clonar y haga clic en *Siguiente*. El disco nuevo hereda las propiedades de la instantánea seleccionada.
. Agregue *Nombre* y *Ruta de acceso al disco*. Actualice las demás configuraciones, como asignar un *nivel de servicio*, y haga clic en *Crear*. Seleccione el nivel de servicio que mejor se adapte a sus necesidades. .Después de terminar


*Create Disk* se ejecuta como un trabajo asíncrono. Podrá:

* Compruebe el estado del trabajo en la lista de trabajos. Para obtener información acerca del seguimiento de trabajos, consulte link:sewebiug_netapp_service_engine_web_interface_overview.html#jobs-and-job-status-indicator["aquí"].
* Una vez finalizado el trabajo, compruebe el estado del disco en la lista *discos*.

