---
sidebar: sidebar 
permalink: sewebiug_back_up_file_shares_and_disks.html 
keywords: netapp, keystone, backup, create, modify, delete, restore 
summary: Crear, modificar y eliminar backups o restaurar desde backups 
---
= Realice una copia de seguridad de los discos y recursos compartidos de archivos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede definir políticas de backup para crear backups de los volúmenes (discos y recursos compartidos de archivos) en su entorno y mantener de forma remota varias copias de los volúmenes primarios.


NOTE: Los backups se crean automáticamente en el sistema cuando se crea o se edita una política de backup para un volumen. No puede crear un backup desde la interfaz de Service Engine de NetApp. Es posible usar la API de backups para crear y gestionar backups para los volúmenes.

Para obtener más información, consulte link:seapiref_backups_apis.html["API de backups"]

La realización de backups de los volúmenes de origen se habilita mediante la tecnología SnapMirror de NetApp, habilitada con los servicios de suscripción de Keystone. Para obtener más información, consulte link:index.html#flex-subscription["aquí"].

Cuando se crea o se edita un volumen, se define su programación de backup. La copia de seguridad se realiza a intervalos previstos y se almacena en un sistema de destino. Para que los backups funcionen, la relación de SnapMirror debe establecerse con el entorno de destino. Los discos y recursos compartidos de archivos replicados de diferentes zonas se almacenan en una máquina virtual de almacenamiento de backup dedicada (máquina virtual de almacenamiento, también conocida como SVM) en cada clúster. Pueden realizarse backups entre dos clústeres de ONTAP separados en zonas diferentes.

Las políticas de backup estándar compatibles con Service Engine de NetApp son:

* Ad hoc
* Todos los días
* Semanal
* Mensual


Para los backups que se crean en el back-end, sus volúmenes deben estar en una `Operational` estado. Para obtener más información acerca de los estados de objeto, vea operativo (para el objeto de origen de una copia de seguridad) link:sewebiug_netapp_service_engine_web_interface_overview.html#object-states["aquí"].

Si su volumen no sigue las políticas de backup estándar compatibles con Service Engine de NetApp, puede hacerlo link:sewebiug_raise_a_service_request.html["elevar una solicitud de servicio"] De la categoría *volumen no estándar* para solucionar el problema.

Puede ver la lista de copias de seguridad creadas para los archivos compartidos y discos en la página *copias de seguridad*. Los backups se muestran en función del inquilino seleccionado.



== Edite una política o una programación de backup

Al crear o editar archivos compartidos y discos, puede definir sus políticas de copia de seguridad. Los backups se realizan en el back-end de acuerdo con las políticas que haya especificado. Para obtener más información, consulte: link:sewebiug_create_a_new_file_share.html["cree un recurso compartido de archivos"] o. link:sewebiug_create_a_new_disk.html["crear un disco"].

.Pasos
. Activar *Política de copia de seguridad*.
. Especifique la zona de backup y la cantidad de backups que se tomarán cada día, cada semana, de forma ad hoc o mensual.
. Haga clic en *Crear*.



NOTE: También es posible programar backups editando la política de backup para un disco o un recurso compartido de archivos existente.



== Modificar o desconectar el origen de una copia de seguridad

Para un objeto de backup seleccionado de un recurso compartido de archivo o disco, puede deshabilitar el backup o desvincular el objeto de backup de su origen y hacer que sea un backup huérfano. Esta operación interrumpe la relación de SnapMirror con el origen. También es posible modificar la cantidad de backups que se deben realizar de forma ad hoc, diaria, semanal o mensual.

.Pasos
. En el panel de navegación de la izquierda, haga clic en *COPIAS de SEGURIDAD*. Es posible ver la lista de backups creados para todos los objetos del entorno.
. Localice el backup en la lista (buscando según el nombre del volumen) y haga clic en el icono de edición, al final de la fila.
. Realice cambios en el origen de la copia de seguridad y en el número de cada tipo de copia de seguridad según sea necesario. Puede romper la relación de SnapMirror con el volumen de origen cambiando el origen de backup a *Ninguno (huérfano)*. Los backups se retienen como backups huérfanos para la restauración, incluso cuando se eliminan los volúmenes de origen. El estado del objeto de backup cambia, y el estado del volumen de origen (huérfano o eliminado) se añade al nombre del volumen de origen en la misma lista. Para obtener más información acerca de los estados de objeto, consulte link:sewebiug_netapp_service_engine_web_interface_overview.html#Object-states["aquí"]
. Haga clic en *Listo*. La copia de Snapshot se modifica. Si ha roto la relación de SnapMirror con el origen, es decir, huérfano al objeto de backup, el nombre del origen de la pestaña *backups* aparece como `deleted`.



NOTE: También puede romper la relación de SnapMirror con el volumen de origen desactivando *Política de copia de seguridad* para el volumen en las pantallas Create Share/Edit Share y Create Disk/Edit Disk.



== Solicitar compatibilidad con backup y restauración

Puede hacerlo link:sewebiug_raise_a_service_request.html["elevar una solicitud de servicio"] para restaurar un recurso compartido de archivos o un disco desde un punto de recuperación específico.

.Pasos
. Seleccione *SUPPORT* en el panel de navegación izquierdo y seleccione *Service Requests*.
. Haga clic en *Nueva solicitud de servicio*.
. Seleccione *Restaurar copia de seguridad* como categoría para la solicitud de servicio.
. Especifique otros detalles y continúe.




== Eliminar un objeto de copia de seguridad

La eliminación de un volumen de backup no utilizado aumenta el espacio de almacenamiento. Para eliminar un volumen de backup y puntos de recuperación del origen eliminado, debe usar la API de backups.


NOTE: Cuando se elimina una copia de seguridad, se eliminan todos los puntos de recuperación de la copia de seguridad. Además, incluso si elimina un disco o un recurso compartido de archivos primario, el backup se conserva como un backup huérfano con todos los puntos de recuperación de la restauración.
