---
sidebar: sidebar 
permalink: sewebiug_view_host_groups.html 
keywords: netapp, keystone, view, host, groups, 
summary: Keystone ver grupos de hosts 
---
= Trabajar con grupos de hosts
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Se definen los grupos de hosts para determinar el acceso a los discos. Según los nodos iniciadores asignados a un grupo de hosts, se determina el acceso de ese grupo de hosts. Es posible añadir un iniciador al crear el grupo de hosts.



== Ver los grupos de hosts

Para ver la lista Grupo de hosts, seleccione *ALMACENAMIENTO EN BLOQUE > grupos de hosts* en el menú.

La lista muestra los grupos de hosts definidos.

En esta página, es posible crear un nuevo grupo de hosts, modificar un grupo de hosts y eliminar un grupo.



= Cree un grupo de hosts

Hay dos formas de crear un grupo de hosts:

* En la página Host Groups, que se describe a continuación.
* Como parte de la creación de un nuevo disco. Use este método cuando necesite crear un grupo de hosts en un almacén de bloques que aún no se ha inicializado. Para obtener más información, consulte link:sewebiug_create_a_new_disk.html#create-a-new-disk["Crear un nuevo disco"].
+
Es posible crear un grupo de hosts vacío y asignarlo a un disco como marcador de posición. Para añadir iniciadores, es necesario actualizar el grupo de hosts vacío y poder acceder al almacenamiento.



.Antes de empezar
Es necesario lo siguiente para crear el grupo de hosts:

* El subarrendatario, la región y la zona en la que se creará el grupo de hosts.



NOTE: Si el almacén de bloques para una combinación de subtenant/zona no se ha inicializado previamente, no podrá crear un grupo de hosts mediante este método. Una alternativa es seguir la link:sewebiug_create_a_new_disk.html#create-a-new-disk["Crear un nuevo disco"] proceso, que permite inicializar el almacén de bloques y crear un grupo de hosts como parte del proceso.

* Un nombre para el grupo de hosts
* El protocolo del grupo de hosts: ISCSI o FCP
* La lista de iniciadores que se van a añadir al grupo: WWPN para los nodos de hosts FC o IQN para los nombres de nodos de host iSCSI.
* Alias para cada iniciador, un alias es un nombre simple para identificar el servidor del iniciador o un puerto/interfaz individual en el servidor. Por ejemplo, Server 4.


.Pasos
. link:sewebiug_view_host_groups.html#view-host-groups["Vea los grupos de hosts"] lista.
. Haga clic en *Crear grupo de hosts*.
. En la página Crear grupo de hosts:
+
.. Seleccione el protocolo: ISCSI o FCP.
.. Seleccione el subinquilino, la región y la zona y el grupo de hosts.


. Escriba un nombre para el grupo de hosts.
. Seleccione el tipo de SO: El sistema operativo del disco.
. Añada los iniciadores para el grupo. Para cada iniciador, especifique el alias y el iniciador.
. Si es necesario, agregue etiquetas (pares clave-valor) al grupo de hosts en la sección Tags.
. Haga clic en *Crear*. Esto crea el grupo de hosts.


.Después de terminar
Una vez creado el grupo de hosts, queda disponible para asignar a discos.



== Modificar grupos de hosts

Es posible modificar un grupo de hosts para añadir, eliminar o corregir iniciadores.

.Tenga en cuenta estos puntos:
* No se puede editar el grupo de hosts si el grupo de hosts no funciona y el icono del lápiz de edición está deshabilitado para esos grupos.
* La modificación de un grupo de hosts modificará el acceso de cada disco asignado al grupo de hosts.
* No puede modificar el alias de un iniciador. Para cambiar el alias, elimine el iniciador del grupo y vuelva a crearlo.


.Pasos
. Vea la link:sewebiug_view_host_groups.html#view-host-groups["Grupos de hosts"] lista.
. Localice el grupo de hosts en la lista, desplácese hasta el final de la fila y haga clic en el icono Editar (icono de lápiz) correspondiente a ese grupo de hosts.
+
Para modificar un iniciador existente, localice el iniciador en la lista, edite el valor del iniciador y haga clic en *Actualizar*.

+
Para añadir un iniciador, realice lo siguiente:

+
.. Haga clic en *Agregar iniciador*.
.. Especifique el alias y el iniciador.
.. Haga clic en *Crear*.
+
Para quitar un iniciador del grupo de hosts, busque el iniciador en la lista y haga clic en el icono Eliminar.



. Haga clic en *Cerrar*.




== Eliminar un grupo de hosts

Puede eliminar un grupo de hosts si no hay discos asignados al grupo de hosts.

.Pasos
. Vea la link:sewebiug_view_host_groups.html#view-host-groups["Grupos de hosts"] lista.
. Busque el grupo de hosts en la lista y haga clic en el icono Delete de ese grupo de hosts.
. En el cuadro de diálogo Confirmar eliminación, introduzca el nombre del grupo de hosts para confirmar que desea eliminar el grupo de hosts.
. Haga clic en *Confirmar*.

