---
sidebar: sidebar 
permalink: sewebiug_modify_user_details.html 
keywords: netapp, keystone, modify, user, details, 
summary: Modifique los detalles del usuario de Keystone 
---
= Modifique los detalles del usuario
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilice este método para modificar los detalles de un usuario. Podrá:

* Modifique el nombre del usuario, el apellido y el nombre para mostrar.
* Agregue o elimine las tenencias a las que tiene acceso el usuario.
* Modifique el rol del usuario en cada tenancy al que tenga acceso el usuario.


.Pasos
. Seleccione *ADMINISTRACIÓN > usuarios*.
. Localice el usuario en la lista y haga clic en el icono Editar.
. En el cuadro de diálogo Editar usuario, realice los cambios necesarios.
. Para cambiar la función del usuario en un área de trabajo, busque el área de trabajo en la lista Tenancies y seleccione la nueva función.
. Para conceder al usuario acceso a otro arrendatario, haga clic en *Agregar arrendatario* y seleccione el arrendatario y la función del usuario en ese arrendatario en los campos de entrada nuevos.
. Para eliminar el acceso del usuario a un puesto de trabajo, busque el área de trabajo en la lista Tenancies y seleccione el icono Eliminar.
. Haga clic en *Actualizar*.

