---
sidebar: sidebar 
permalink: sewebiug_managing_tenants_and_subtenants.html 
keywords: netapp, keystone, managing, subtenants, 
summary: Gestión de subinquilinos de Keystone 
---
= Gestión de inquilinos y subinquilinos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede ver y gestionar sus inquilinos y subinquilinos mediante el motor de servicios de NetApp. El soporte de NetApp configura el soporte inicial para proveedores de servicios/partners e inquilinos. La región, la zona y la suscripción ya están configuradas por soporte y están disponibles cuando se crean inquilinos y subinquilinos bajo el servicio.



== Clientes

Si es un administrador asociado, puede crear, modificar y eliminar un inquilino de *ADMINISTRACIÓN* > *arrendatarios*. Los administradores de inquilinos solo pueden ver sus suscripciones de inquilino y sus subinquilinos respectivos. Para los inquilinos bajo el servicio del partner, también puede definir la red.



=== Cree un inquilino

Puede crear un inquilino si es un administrador de partner. También puede crear y gestionar redes para cada inquilino. Para obtener más información sobre la creación de redes, consulte link:sewebiug_define_network_configurations.html["Defina las configuraciones de red con subredes"].

.Pasos
. Haga clic en *Crear arrendatario*.
. Agregue un nombre y el código. El código que representa al inquilino debe ser único dentro de una instancia de Service Engine de NetApp y estar compuesto por caracteres en minúscula.
. Haga clic en *Crear*.



NOTE: Sólo puede modificar el nombre y la descripción de un arrendatario existente. Además, no puede eliminar un inquilino que tenga subinquilinos o componentes de almacenamiento asociados.



== Subinquilinos

Si es un administrador de partners o un administrador de inquilinos, puede ver y gestionar los subinquilinos.



=== Cree un subarrendatario

Si es un administrador de partner o un administrador de arrendatario, puede crear, modificar y eliminar un subarrendatario de *ADMINISTRACIÓN* > *subarrendatarios*. También puede crear y administrar redes para cada subarrendatario.

Para obtener más información sobre la creación de redes, consulte link:sewebiug_define_network_configurations.html["Defina las configuraciones de red con subredes"].

.Pasos
. Haga clic en *Crear subarrendatario*.
. Agregue un nombre y el código. El código que representa al subinquilino debe ser único dentro de una instancia de Service Engine de NetApp y estar compuesto por caracteres en minúscula.
. Haga clic en *Crear*.



NOTE: Sólo puede modificar el nombre de un subarrendatario existente. Además, no puede eliminar un subinquilino que tenga asociados componentes de almacenamiento.
