---
sidebar: sidebar 
permalink: sewebiug_create_an_s3_key_for_a_user.html 
keywords: netapp, keystone, create, S3, key, user, 
summary: Keystone cree una clave S3 para un usuario 
---
= Cree una clave S3 para un usuario
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Use este método para crear una clave de S3 para un usuario.

Asegúrese de capturar la clave inmediatamente después de crearla. No hay forma de recuperar los detalles de las claves después de que se hayan creado.

.Pasos
. Vea el usuario de almacenamiento de objetos link:sewebiug_view_the_object_storage_group_and_users.html["Ver los usuarios y el grupo de almacenamiento de objetos"].
. Asegúrese de que el subarrendatario correcto está seleccionado y ha hecho clic en la ficha *usuarios*.
. Localice el usuario en la lista y haga clic en el icono de clave de ese grupo.
+
Para obtener información detallada sobre cómo trabajar con elementos de las listas, consulte link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view-actions["Acciones de vista de lista"].

. Aparece el cuadro de diálogo *Administrar claves S3* que muestra la lista de claves para el usuario. Para obtener más información sobre las teclas, consulte https://docs.netapp.com/us-en/storagegrid-116/s3/bucket-and-group-access-policies.html#specify-permissions-in-a-policy["Especificar permisos en una directiva"].
. Si no hay claves existentes para el usuario, haga clic en *Crear clave S3* para ver los campos a fin de crear una clave.
. Si desea que la clave caduque, especifique la fecha de caducidad y la hora de caducidad en UTC. De lo contrario, deje los valores predeterminados en estos campos.
. Para crear la clave, haga clic en la Marca de verificación. Aparece el cuadro de diálogo *Detalles de la clave de S3* que muestra la clave de acceso y la clave secreta.
. Copie tanto las claves de acceso como las claves secretas para asesorar al usuario sobre los detalles.
+
Asegúrese de capturar los detalles de la clave antes de cerrar el cuadro de diálogo *Detalles de la clave de S3*. Tras cerrarse, los detalles de la clave se oscurecerán y no podrá recuperarlos.

. Haga clic en *Cerrar*.
. Haga clic en *Cerrar* de nuevo para cerrar el cuadro de diálogo Administrar claves S3.

