---
sidebar: sidebar 
permalink: sewebiug_modify_an_object_storage_group.html 
keywords: netapp, keystone, modify, object, storage, group 
summary: Keystone modifique un grupo de almacenamiento de objetos 
---
= Modificar un grupo de almacenamiento de objetos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Use este método para modificar los detalles de un grupo de almacenamiento de objetos, como el nombre del grupo y la política de S3.

.Pasos
. Vea el grupo de almacenamiento de objetos link:sewebiug_view_the_object_storage_group_and_users.html["Ver los usuarios y el grupo de almacenamiento de objetos"].
. Asegúrese de que el subarrendatario correcto está seleccionado y ha hecho clic en la ficha *grupos*.
. Localice el grupo en la lista y haga clic en el icono de edición de ese grupo.
+
Para obtener información detallada sobre cómo trabajar con elementos de las listas, consulte link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view-actions["Acciones de vista de lista"].

. En el cuadro de diálogo *Editar grupo*, modifique la directiva S3 aplicable al grupo. Para obtener más información sobre las políticas de S3, consulte https://docs.netapp.com/us-en/storagegrid-116/s3/bucket-and-group-access-policies.html#specify-permissions-in-a-policy["Especificar permisos en una directiva"].
. Puede agregar sentencias de directiva adicionales según sea necesario.
. Haga clic en *Actualizar*. Esto crea un trabajo para modificar el grupo con la configuración especificada. Para obtener información acerca del seguimiento de trabajos, consulte link:sewebiug_netapp_service_engine_web_interface_overview.html#jobs-and-job-status-indicator["aquí"].

