---
sidebar: sidebar 
permalink: sewebiug_create_file_share_from_snapshot.html 
keywords: netapp, keystone, create, file share, snapshot 
summary: Cree un recurso compartido de archivos a partir de una instantánea 
---
= Cree un recurso compartido de archivos a partir de una instantánea
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede crear un nuevo recurso compartido de archivos a partir de una instantánea existente. El nuevo recurso compartido de archivos, clonado desde la instantánea, tiene las mismas propiedades que el recurso compartido de archivos desde el que se crea la instantánea.

.Pasos
. Seleccione *SERVICIOS de ARCHIVOS* en el panel de navegación izquierdo y seleccione *Recursos compartidos*.
. Haga clic en *Crear recurso compartido* y seleccione *Clonar desde instantánea*. Como alternativa, si conoce el recurso compartido cuya instantánea desea utilizar para la clonación, puede localizar el recurso compartido de archivos y hacer clic en el botón de copia situado junto a él. El recurso compartido debe estar en un estado operativo. Para obtener más información acerca de los estados de objeto, consulte link:sewebiug_netapp_service_engine_web_interface_overview.html#object-states["estados de objeto"]. Aparece la pantalla *Crear recurso compartido desde Snapshot* con todos los archivos compartidos para el arrendatario. Puede filtrar los recursos compartidos de archivos por región, zona y subarrendatario. Puede seleccionar cualquier recurso compartido de archivos que esté en estado operativo.
. Active la casilla de verificación situada junto al recurso compartido de archivos que desee y haga clic en *Siguiente*. Se muestran las instantáneas del recurso compartido de archivos.
+

NOTE: Para el recurso compartido de archivos seleccionado, si se crean algunas copias de Snapshot en el entorno de SnapCenter fuera del motor de servicio de NetApp, se pueden encontrar estas copias de Snapshot importadas y enumeradas para su selección. Es posible seleccionar estas snapshots importadas y clonar los nuevos recursos compartidos de archivos desde ellas.

+
Puede buscar una copia de Snapshot en particular o seleccionar el tipo de programación para filtrar las copias de Snapshot.

. Seleccione la casilla de verificación situada junto a la instantánea desde la que desea clonar y haga clic en *Siguiente*. El nuevo recurso compartido de archivos hereda las propiedades de la instantánea seleccionada.
. Añada *Nombre* y *Ruta compartida*. Actualice las demás configuraciones, como asignar un *nivel de servicio*, y haga clic en *Crear*. Seleccione el nivel de servicio que mejor se adapte a sus necesidades.


.Después de terminar
* Para recursos compartidos de tipo CIFS only: Para que los recursos compartidos estén disponibles por nombre de host, el administrador de dominio debe actualizar los registros DNS con el nombre del servidor CIFS y la dirección IP. De lo contrario, solo se puede acceder al recurso compartido a través de la dirección IP. Por ejemplo:
+
** Con los registros DNS actualizados, utilice el nombre de host o IP para acceder al recurso compartido: Por ejemplo file://hostname/share["\\hostname\share"^] o. file://IP/share["\\IP\share"^]
** Sin actualizar registros DNS, debe utilizar la dirección IP para acceder al recurso compartido, es decir file://IP/share["\\IP\share"^]


* *Create Share* se ejecuta como un trabajo asíncrono. Podrá:
+
** Compruebe el estado del trabajo en la lista de trabajos. Para obtener información acerca del seguimiento de trabajos, consulte link:sewebiug_netapp_service_engine_web_interface_overview.html#jobs-and-job-status-indicator["aquí"].
** Una vez terminado el trabajo, compruebe el estado del recurso compartido en la lista *shares*.



