---
sidebar: sidebar 
permalink: sewebiug_view_disks.html 
keywords: netapp, keystone, view, buckets, 
summary: Discos de vista Keystone 
---
= Ver discos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La lista discos muestra los discos que pertenecen al arrendatario seleccionado. Para ver la lista, seleccione *BLOQUEAR ALMACENAMIENTO > discos* en el menú.

Los discos que ya forman parte de su entorno actual y pertenecen a los equipos virtuales de almacenamiento configurados en su motor de servicios de NetApp, también se pueden ver en esta pantalla y se pueden gestionar como parte de sus servicios de suscripción flexible (suscripción flexible) de NetApp Keystone. Los discos aprovisionados fuera del motor de servicio de NetApp se importan de forma periódica y se enumeran en esta página con los códigos de estado correspondientes.

Si los discos importados se encuentran en estándares aceptables en el motor de servicio de NetApp, es decir, si todos los parámetros necesarios para hacer que los discos estén operativos están disponibles, se importarán con el estado tal como `Operational` Y se pueden gestionar directamente mediante el motor de servicio de NetApp. Sin embargo, es posible que algunos discos no estén en el mismo estándar que los discos existentes en el motor de servicio de NetApp. Después de importar, estos discos se clasifican con `Imported` o. `Non-Standard` estado. Para comprender los Estados de los discos y los pasos que se deben seguir para hacerlos operativos, consulte link:sewebiug_netapp_service_engine_web_interface_overview.html#object-states["estados de objeto"]

En la lista discos, consulte información sencilla. Para obtener más información acerca de cómo utilizar las funciones de una lista, consulte link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view-actions["Acciones de vista de lista"].

* Nombre de disco
* Ruta al disco
* Tamaño de disco
* Protocolo
* Subinquilino al que pertenece el disco
* Zona en la que existe el disco
* Estado operativo

