---
sidebar: sidebar 
permalink: sewebiug_view_the_object_storage_group_and_users.html 
keywords: netapp, keystone, view, object, storage, group, users, 
summary: Keystone permite ver el grupo de almacenamiento de objetos y los usuarios 
---
= Ver los usuarios y el grupo de almacenamiento de objetos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La lista Administración de usuarios muestra los usuarios y grupos de almacenamiento de objetos de un subinquilino especificado.

.Pasos
. En el menú, seleccione *ALMACENAMIENTO DE OBJETOS > Gestión de usuarios*.
. Utilice el menú desplegable subarrendatario para seleccionar otro subarrendatario si es necesario.
. Utilice las fichas *usuarios* y *grupos* para alternar la visualización entre usuarios y grupos.
+
** La lista usuarios muestra los usuarios de almacenamiento de objetos definidos para el subarrendatario seleccionado. Para cada usuario, muestra su nombre y los grupos de almacenamiento de objetos a los que pertenecen.
** La lista grupos muestra los grupos de almacenamiento de objetos definidos para el subarrendatario seleccionado. Muestra el nombre del grupo y la política S3 asignada a ese grupo. Para obtener más información sobre los grupos de bloques y las políticas de S3, consulte https://["Políticas de acceso a bloques y grupos"].
+
Para obtener más información acerca de cómo utilizar las funciones de una lista, consulte link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view-actions["Acciones de vista de lista"].




