---
sidebar: sidebar 
permalink: sewebiug_view_shares.html 
keywords: netapp, keystone, view, shares, 
summary: Recursos compartidos con vistas Keystone 
---
= Ver recursos compartidos de archivos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La lista *shares* muestra los archivos compartidos que pertenecen al arrendatario seleccionado. Para ver la lista, seleccione *SERVICIOS de ARCHIVOS > Recursos compartidos* en el menú.

Los recursos compartidos de archivos que ya forman parte de su entorno existente y pertenecen a los equipos virtuales de almacenamiento configurados en su motor de servicios de NetApp, también se pueden ver en esta pantalla y se pueden gestionar como parte de sus servicios de suscripción flexible (suscripción flexible) de NetApp Keystone. Los recursos compartidos de archivos aprovisionados fuera del motor de servicio de NetApp se importan de forma periódica y se enumeran en esta página con los códigos de estado correspondientes.

Si los recursos compartidos de archivos importados se encuentran en estándares aceptables en el motor de servicio de NetApp, es decir, todos los parámetros necesarios para hacer que los recursos compartidos estén disponibles, se importan con el estado como `Operational` Y se pueden gestionar directamente mediante el motor de servicio de NetApp. Sin embargo, es posible que algunos recursos compartidos no sean del mismo estándar que los recursos compartidos existentes en el motor de servicio de NetApp. Después de importar, estos recursos compartidos de archivos se categorizan con `Imported` o. `Non-Standard` estado. Para comprender los Estados de los volúmenes y los pasos que se deben seguir para hacerlos operativos, consulte link:https://docs.netapp.com/us-en/keystone/sewebiug_netapp_service_engine_web_interface_overview.html#Object-states["estados de objeto"]

En la lista de recursos compartidos, se muestra información sencilla sobre cada recurso compartido. Para obtener más información acerca de cómo utilizar las funciones de una lista, consulte link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view["Vista de lista"].

* Nombre del recurso compartido
* Del servidor en el que reside
* Comparta la ruta
* Ruta de uso compartido de CIFS (utilizada para montar el recurso compartido de CIFS con integración de DNS)
* Subinquilino al que pertenece
* Zona en la que existe
* Nivel de servicio
* Estado operativo (operativo, actualización o contacto con el soporte de)
* Fecha de creación

