---
sidebar: sidebar 
permalink: sewebiug_modify_a_file_share.html 
keywords: netapp, keystone, modify, file, share, 
summary: Keystone modifique un recurso compartido de archivos 
---
= Modificar un recurso compartido de archivos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Se puede cambiar el nombre del recurso compartido, el nivel de servicio, la capacidad, la política de Snapshot, la política de exportación, Lista de control de acceso (ACL) y etiquetas en un recurso compartido de archivos.


NOTE: Con este método, puede mover los recursos compartidos a diferentes niveles de servicio si están disponibles. Sólo puede cambiar el tipo de recurso compartido si el servidor admite los servicios correspondientes.

.Antes de empezar
El recurso compartido de archivos debe estar en estado operativo. Para comprender los Estados de los volúmenes y los pasos que se deben seguir para hacerlos operativos, consulte link:sewebiug_view_disks.html["Ver discos"] y.. link:sewebiug_netapp_service_engine_web_interface_overview.html#object-states["estados de objeto"]

.Pasos
. Vea la link:sewebiug_view_shares.html#view-shares["Lista de recursos compartidos"].
. Localice el recurso compartido en la lista y haga clic en el icono Edit para ese recurso compartido. (Para obtener información detallada sobre cómo trabajar con elementos de las listas, consulte link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view["Acciones de vista de lista"]).
. Realice los cambios necesarios; para ver las descripciones de los campos, consulte link:sewebiug_create_a_new_file_share.html["Cree un nuevo recurso compartido de archivos"].
. Haga clic en *Listo*. Esto crea un trabajo para modificar el recurso compartido.


.Después de terminar
El recurso compartido de modificación se ejecuta como un trabajo asíncrono. Podrá:

* Compruebe el estado del trabajo en la lista de trabajos. Para obtener información acerca del seguimiento de trabajos, consulte link:sewebiug_netapp_service_engine_web_interface_overview.html#jobs-and-job-status-indicator["aquí"].
* Una vez terminado el trabajo, compruebe el estado del recurso compartido en la lista de recursos compartidos.

