---
sidebar: sidebar 
permalink: sewebiug_create_an_object_storage_group.html 
keywords: netapp, keystone, create, object, storage, group, 
summary: Keystone cree un grupo de almacenamiento de objetos 
---
= Cree un grupo de almacenamiento de objetos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Use este método para crear un grupo de almacenamiento de objetos.

.Pasos
. Vea la lista de grupos de almacenamiento de objetos desde *ALMACENAMIENTO DE OBJETOS > Administración de usuarios > grupos*.
. Asegúrese de que el subarrendatario correcto está seleccionado y ha hecho clic en la ficha *grupos*.
. Haga clic en *Crear grupo*.
. En el cuadro de diálogo Create Group, introduzca el nombre del grupo.
. Seleccione la política de S3 de la lista. Para obtener más información sobre las políticas de S3, consulte https://["Especificar permisos en una directiva"].
. Haga clic en *Crear*. Esto crea un trabajo para crear el grupo con la configuración especificada.


.Después de terminar
El grupo de almacenamiento de objetos Create se ejecuta como un trabajo asíncrono. Puede comprobar el estado del trabajo en la lista de trabajos. Para obtener información acerca del seguimiento de trabajos, consulte link:sewebiug_netapp_service_engine_web_interface_overview.html#jobs-and-job-status-indicator["aquí"].
