---
sidebar: sidebar 
permalink: sewebiug_partner_service_provider.html 
keywords: netapp, service, engine, web, portal, partner, service provider 
summary: Funciones del partner del motor de servicios de NetApp y del proveedor de servicios 
---
= Funciones y operaciones de proveedores de servicios y clientes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
En función de su rol de proveedor de servicios o partner (utilizado indistintamente) o administrador de un cliente o inquilino (utilizado de manera intercambiable), se determinan las vistas y funciones del portal web del motor de servicio de NetApp.



== Actividades que puede realizar como administrador de proveedor de servicios

Como administrador de proveedor de servicios en un entorno multi-tenant, puede realizar las funciones de aprovisionamiento, creación de informes, facturación y gestión de los clientes que tengan sus propias suscripciones a través de la interfaz de usuario web del motor de servicios de NetApp. Puede realizar las siguientes funciones:

* Ver el almacenamiento suscrito y aprovisionado como parte de su servicio de suscripción de Keystone.
+

NOTE: Como prestación de un servicio, puede vender más capacidad a sus clientes de la que adquirió a NetApp (exceso de suscripción). Las suscripciones de inquilinos pueden ampliarse más allá del periodo de suscripción de Keystone actual, pero se muestra una advertencia en el momento de la creación de la suscripción, y en consolas/informes.

* Crear, ver, modificar y eliminar inquilinos, subinquilinos, y usuarios.
* Ver zonas y regiones de sus suscripciones.
* Gestione y aloje varios inquilinos dentro del servicio de suscripción de Keystone: Cree y gestione suscripciones de inquilinos y consulte sus propios detalles de suscripción de Keystone.
+

NOTE: Las suscripciones de inquilinos se pueden crear en función de las zonas correspondientes y de las suscripciones de Keystone. Se crean según los niveles de servicio proporcionados bajo la capacidad suscrita de tu suscripción a Keystone.

* Cree servidores de archivos o almacenes de bloques e inicialice el almacenamiento de bloques, archivos y objetos cuando conozca los requisitos de red para aprovisionar cada tipo de almacenamiento para sus clientes.
* También puede crear y administrar subredes para sus inquilinos,
* Consulta los recursos compartidos de archivos, los discos y los bloques creados como parte de tu suscripción a Keystone. También cree y gestione grupos de almacenamiento de objetos y usuarios.
* Cree informes de consumo comparados con su suscripción a Keystone, las suscripciones de inquilinos y el uso para todos los inquilinos para su uso en los respectivos sistemas de facturación y calificación.
* Consulte la facturación y la creación de informes para todos los clientes y clientes, y solo para el almacenamiento suscrito o aprovisionado.
* Vea y gestione las solicitudes de servicios que han generado los clientes dentro de su propia herramienta de solicitud de servicio (integrada con OpsRamp/GSSC).




== Actividades que puede realizar como administrador de clientes/inquilinos

Como administrador de inquilinos, puede ver los detalles de suscripción de su propio tenancy y realizar tareas administrativas para sus subinquilinos. Es posible realizar las siguientes acciones:

* Consulte el almacenamiento suscrito y aprovisionado como parte de su servicio de suscripción de inquilinos.
* Gestione y edite subinquilinos para su tenancy.
* Vea las zonas, regiones, subinquilinos y subredes.
* Vea los servidores de archivos creados por los proveedores de servicios.
* Cree recursos compartidos de archivos, discos y bloques, y asigne niveles de servicio a ellos.
* Vea informes para inquilinos y subinquilinos en *Informes > utilización de la capacidad* para ver los datos de consumo sólo para el almacenamiento suscrito o aprovisionado para su usuario y sus subinquilinos.
* Vea informes para inquilinos y subinquilinos en *Informes > rendimiento* para ver el rendimiento y el cumplimiento del servicio de su cliente para cada servicio suscrito y servicios complementarios (Protección de datos y Protección avanzada).
+

NOTE: Para suscripciones adicionales, puede utilizar la herramienta de solicitud de servicio.


