---
sidebar: sidebar 
permalink: sewebiug_managing_azure_volumes.html 
keywords: netapp, keystone, managing, azure, volumes, 
summary: Keystone para la gestión de volúmenes de Azure 
---
= Gestionar volúmenes de Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
En esta sección se describe cómo gestionar volúmenes de Azure.


NOTE: Para gestionar volúmenes de Azure, es necesario acceder al administrador de clientes.

En esta sección se describe cómo realizar las siguientes tareas:

* Consulte una lista de volúmenes de Azure.
* Añada un volumen de Azure.
* Modifique los detalles del volumen de Azure.
* Elimine un volumen de Azure.




== Consulte una lista de volúmenes de Azure

La lista de volúmenes de Azure muestra una lista de pools de volúmenes de Azure para un subinquilino y una ubicación especificados. Para ver la lista, seleccione *SERVICIOS de ARCHIVOS > volúmenes de Azure* en el menú.

La lista muestra información sencilla sobre cada volumen de Azure. Los iconos de acción junto a cada volumen de Azure permiten modificar o eliminar el volumen de Azure.



== Añada un volumen de Azure

En esta sección se describe cómo añadir un volumen de Azure.

.Antes de empezar
Necesitará:

* El subinquilino al que pertenece el volumen de Azure
* La cuenta ANF
* Red virtual (vnet) y subred de Azure
* El pool de capacidad para alojar el volumen
* Un nombre para el volumen
* La ruta del archivo
* La cuota (tamaño) del volumen


.Pasos
. Seleccione *SERVICIOS de ARCHIVOS > Azure Volumes* en el menú.
. Haga clic en *Crear*.
. En el cuadro de diálogo Create Azure Volume, especifique el subinquilino, la cuenta ANF, el vnet, la subred, el pool de capacidad, el nombre del volumen, la ruta de archivo y la cuota. Asegúrese de introducir una ruta de archivo única para crear un volumen correctamente.
. Si es necesario, agregue etiquetas al volumen.
. Haga clic en *Crear*. Cuando se crea un volumen de Azure, el estado del volumen cambia a. `Succeeded` (Puede verse en la lista de volúmenes de Azure).




== Modifique los detalles del volumen de Azure

Utilice este método para modificar los detalles de un volumen de Azure. Puede modificar la ruta de acceso y la cuota del archivo y agregar o quitar etiquetas.

.Pasos
. Seleccione *SERVICIOS de ARCHIVOS > Azure Volumes* en el menú.
. En la lista, busque el volumen de Azure y haga clic en el icono de edición.
. En el cuadro de diálogo Manage Azure Volume, realice los cambios necesarios. Si va a modificar la ruta de acceso o cuota de archivo, asegúrese de que la ruta de acceso de archivo sea única y que la cuota no supere la cuota disponible en el pool.
. Haga clic en *Actualizar*.




== Elimine un volumen de Azure

Use este método para eliminar un volumen de Azure.

.Pasos
. Seleccione *SERVICIOS de ARCHIVOS > Azure Volumes* en el menú.
. Localice el volumen de Azure en la lista y haga clic en el icono de eliminar.
. En el cuadro de diálogo Confirmar eliminación, introduzca el nombre del volumen de Azure que desea eliminar.
. Haga clic en *Confirmar*.

