---
sidebar: sidebar 
permalink: sewebiug_modify_file_server.html 
keywords: netapp, keystone, modify, file, server, 
summary: Modificar servidor de archivos 
---
= Modificar servidor de archivos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede realizar los siguientes cambios en un servidor existente:

. Cambie el nombre del servidor
. Habilite el servidor CIFS y especifique el nombre de usuario y la contraseña de Active Directory, el dominio de Active Directory, el servidor DNS, el nombre del servidor y, opcionalmente, la unidad organizativa de Active Directory. Las credenciales de Active Directory deben corresponder a un usuario que tenga el privilegio de unirse a un equipo al dominio de Active Directory.
. Active la recuperación ante desastres asíncrona mediante la especificación de una región o zona a la que se debe replicar el servidor.



NOTE: Si la recuperación ante desastres asíncrona ya está habilitada, no se puede deshabilitar. Para obtener más información, consulte link:sewebiug_billing_accounts,_subscriptions,_services,_and_performance.html#disaster-recovery["Recuperación tras siniestros"].

.Pasos
. Vea la link:sewebiug_view_servers.html#view-servers["Servidores de archivos"].
. Busque el servidor en la lista y haga clic en el icono Editar de ese servidor. (Para obtener información detallada sobre cómo trabajar con elementos de las listas, consulte link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view["Acciones de vista de lista"]).
. Realice los cambios necesarios; consulte link:sewebiug_create_a_file_server.html["Cree un servidor de archivos"] para obtener descripciones de campos.
. Haga clic en *Listo*. Esto crea un trabajo para modificar el servidor.


.Después de terminar
El servidor de modificación se ejecuta como un trabajo asíncrono. Podrá:

* Compruebe el estado del trabajo en la lista de trabajos. Para obtener información acerca del seguimiento de trabajos, consulte link:https://docs.netapp.com/us-en/keystone/sewebiug_netapp_service_engine_web_interface_overview.html#jobs-and-job-status-indicator["aquí"].
* Una vez terminado el trabajo, compruebe el estado del servidor en la lista servidores.

