---
sidebar: sidebar 
permalink: sewebiug_create_an_adhoc_snapshot_of_a_disk.html 
keywords: netapp, keystone, create, adhoc, snapshot, disk 
summary: Keystone cree una snapshot ad hoc de un disco 
---
= Crear una instantánea ad hoc de un disco
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
En esta sección se describe cómo crear una instantánea ad hoc de un disco.

.Pasos
. Vea la link:sewebiug_view_disks.html#view-disks["Lista Disks"].
. Localice el disco en la lista y haga clic en el icono de instantánea de ese disco. (Para obtener información detallada sobre cómo trabajar con elementos de las listas, consulte link:sewebiug_netapp_service_engine_web_interface_overview#list-view["Acciones de vista de lista"]).
. En el cuadro de diálogo Crear instantánea, introduzca un nombre para la instantánea y haga clic en *Crear*.


.Después de terminar
La copia Snapshot puede tardar unos minutos en estar disponible. Cuando esté disponible, puede crear otro disco clonando esta snapshot. Para obtener más información, consulte link:sewebiug_create_a_disk_from_a_snapshot.html["Crear un disco a partir de una instantánea"].
