---
sidebar: sidebar 
permalink: sewebiug_modify_a_disk.html 
keywords: netapp, keystone, modify, disk, 
summary: Modifique un disco Keystone 
---
= Modificar un disco
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Se puede modificar el nombre del disco, la asignación del grupo de hosts, el nivel de servicio, la capacidad y la política Snapshot. Con este método, puede mover los discos a diferentes niveles de servicio si está disponible.

.Antes de empezar
El disco debe estar en estado operativo. Para comprender los Estados de los volúmenes y los pasos que se deben seguir para hacerlos operativos, consulte link:sewebiug_view_disks.html["Ver discos"] y.. link:sewebiug_netapp_service_engine_web_interface_overview.html#object-states["estados de objeto"]

.Pasos
. Vea la link:sewebiug_view_disks.html#view-disks["Lista Disks"].
. Localice el disco en la lista y haga clic en el icono Edit correspondiente a ese disco. (Para obtener información detallada sobre cómo trabajar con elementos de las listas, consulte link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view["Acciones de vista de lista"]).
. Realice los cambios necesarios; consulte link:sewebiug_create_a_new_disk.html["Crear un nuevo disco"] para obtener descripciones de campos.
. Haga clic en *Listo*. Esto crea un trabajo para modificar el disco.


.Después de terminar
El disco de modificación se ejecuta como un trabajo asíncrono. Podrá:

* Compruebe el estado del trabajo en la lista de trabajos. Para obtener información acerca del seguimiento de trabajos, consulte link:sewebiug_netapp_service_engine_web_interface_overview.html#jobs-and-job-status-indicator["aquí"].
* Una vez finalizado el trabajo, compruebe el estado del disco en la lista discos.

